// Real-life phrase packs for Kannada families in the USA (and anyone visiting Karnataka).
// Everyday spoken Kannada, the way families actually talk (ಮಾಡ್ತೀನಿ rather than ಮಾಡುತ್ತೇನೆ).
// Each pack: phrases [kannada, how to say it, English] and a short chat: Gini plays someone
// (Ajji on the phone, Amma at the temple, an auto driver) and the learner picks or says an answer.
// for: "all" | "kids" | "grown"  (kids see "all" + "kids"; grown-ups see everything)
// Please have a Kannada teacher review every line before families use it.

const L = (kn, rom, en) => [kn, rom, en];

export const PACKS = [
  {
    id: "calling", icon: "📱", en: "Calling India", kn: "ಊರಿಗೆ ಫೋನ್", for: "all", who: "Ajji",
    goal: "Phone and video calls with Ajji, Tata and family back home.",
    phrases: [
      L("ಹಲೋ ಅಜ್ಜಿ, ಹೇಗಿದ್ದೀರಾ?", "halo ajji, heegiddiiraa?", "Hello Ajji, how are you?"),
      L("ನಾನು ಚೆನ್ನಾಗಿದ್ದೀನಿ.", "naanu chennaagiddiini.", "I'm fine."),
      L("ಊಟ ಆಯ್ತಾ?", "uuTa aaytaa?", "Have you eaten?"),
      L("ನಿಮ್ಮನ್ನು ತುಂಬಾ ಮಿಸ್ ಮಾಡ್ತೀನಿ.", "nimmannu tumbaa mis maaDtiini.", "I miss you a lot."),
      L("ಅಲ್ಲಿ ಈಗ ಎಷ್ಟು ಗಂಟೆ?", "alli iiga eshTu ganTe?", "What time is it there now?"),
      L("ಇಲ್ಲಿ ಈಗ ರಾತ್ರಿ.", "illi iiga raatri.", "It's night here now."),
      L("ನಿಮಗೆ ಕೇಳಿಸ್ತಿದೆಯಾ?", "nimage keeListideyaa?", "Can you hear me?"),
      L("ಸ್ವಲ್ಪ ಜೋರಾಗಿ ಮಾತಾಡಿ.", "swalpa jooraagi maataaDi.", "Please speak a little louder."),
      L("ಆರೋಗ್ಯ ಹೇಗಿದೆ?", "aaroogya heegide?", "How is your health?"),
      L("ಬೇಗ ಬನ್ನಿ!", "beega banni!", "Come soon!"),
      L("ಮತ್ತೆ ಫೋನ್ ಮಾಡ್ತೀನಿ.", "matte phoon maaDtiini.", "I'll call again."),
      L("ಹುಷಾರಾಗಿರಿ.", "hushaaraagiri.", "Take care."),
    ],
    chat: [
      { gini: L("ಹಲೋ ಮರಿ! ಹೇಗಿದ್ದೀಯಾ?", "halo mari! heegiddiiyaa?", "Hello dear! How are you?"), answers: [L("ನಾನು ಚೆನ್ನಾಗಿದ್ದೀನಿ ಅಜ್ಜಿ. ನೀವು?", "naanu chennaagiddiini ajji. niivu?", "I'm fine Ajji. You?"), L("ಹಲೋ ಅಜ್ಜಿ! ನಿಮ್ಮನ್ನು ಮಿಸ್ ಮಾಡ್ತೀನಿ.", "halo ajji! nimmannu mis maaDtiini.", "Hello Ajji! I miss you.")] },
      { gini: L("ನಾನೂ ಚೆನ್ನಾಗಿದ್ದೀನಿ. ಊಟ ಆಯ್ತಾ?", "naanuu chennaagiddiini. uuTa aaytaa?", "I'm fine too. Have you eaten?"), answers: [L("ಹೌದು, ಊಟ ಆಯ್ತು.", "haudu, uuTa aaytu.", "Yes, I've eaten."), L("ಇನ್ನೂ ಇಲ್ಲ, ಈಗ ತಿಂತೀನಿ.", "innuu illa, iiga tintiini.", "Not yet, I'll eat now.")] },
      { gini: L("ಇವತ್ತು ಶಾಲೆಯಲ್ಲಿ ಏನು ಮಾಡಿದೆ?", "ivattu shaaleyalli eenu maaDide?", "What did you do at school today?"), answers: [L("ಆಟ ಆಡಿದೆ.", "aaTa aaDide.", "I played games."), L("ಕನ್ನಡ ಕಲಿತೆ!", "kannaDa kalite!", "I learnt Kannada!")] },
      { gini: L("ಶಭಾಷ್! ಮತ್ತೆ ಫೋನ್ ಮಾಡು, ಆಯ್ತಾ?", "shabhaash! matte phoon maaDu, aaytaa?", "Well done! Call again, okay?"), answers: [L("ಆಯ್ತು ಅಜ್ಜಿ. ಬೈ!", "aaytu ajji. bai!", "Okay Ajji. Bye!"), L("ಹುಷಾರಾಗಿರಿ ಅಜ್ಜಿ!", "hushaaraagiri ajji!", "Take care, Ajji!")] },
    ],
  },
  {
    id: "visit", icon: "✈️", en: "Ajji and Tata visit the US", kn: "ಅಜ್ಜಿ ತಾತ ಬಂದಾಗ", for: "all", who: "Tata",
    goal: "Welcoming grandparents, looking after them, and showing them around.",
    phrases: [
      L("ಸ್ವಾಗತ! ಪ್ರಯಾಣ ಹೇಗಿತ್ತು?", "swaagata! prayaaNa heegittu?", "Welcome! How was the journey?"),
      L("ನಿಮಗೆ ಸುಸ್ತಾಗಿದೆಯಾ?", "nimage sustaagideyaa?", "Are you tired?"),
      L("ಸ್ವಲ್ಪ ವಿಶ್ರಾಂತಿ ತಗೊಳ್ಳಿ.", "swalpa vishraanti tagoLLi.", "Please rest a little."),
      L("ಇಲ್ಲಿ ತುಂಬಾ ಚಳಿ ಇದೆ.", "illi tumbaa chaLi ide.", "It's very cold here."),
      L("ಸ್ವೆಟರ್ ಹಾಕಿಕೊಳ್ಳಿ.", "sweTar haakikoLLi.", "Please wear a sweater."),
      L("ಕಾಫಿ ಬೇಕಾ?", "kaaphi beekaa?", "Would you like coffee?"),
      L("ಇವತ್ತು ಪಾರ್ಕ್‌ಗೆ ಹೋಗೋಣ.", "ivattu paark-ge hoogooNa.", "Let's go to the park today."),
      L("ಕಾರಿನಲ್ಲಿ ಸೀಟ್ ಬೆಲ್ಟ್ ಹಾಕಿ.", "kaarinalli siiT belT haaki.", "Put on your seat belt in the car."),
      L("ನನ್ನ ಶಾಲೆ ತೋರಿಸ್ತೀನಿ.", "nanna shaale tooristiini.", "I'll show you my school."),
      L("ನಿಮಗೆ ಏನು ಬೇಕು ಹೇಳಿ.", "nimage eenu beeku heeLi.", "Tell me what you need."),
      L("ನೀವು ಇಲ್ಲಿ ಇರೋದು ನಮಗೆ ತುಂಬಾ ಖುಷಿ.", "niivu illi iroodu namage tumbaa khushi.", "We're so happy you're here."),
      L("ಇನ್ನೂ ಸ್ವಲ್ಪ ದಿನ ಇರಿ!", "innuu swalpa dina iri!", "Stay a few more days!"),
    ],
    chat: [
      { gini: L("ನಮಸ್ಕಾರ ಮರಿ! ನಾವು ಬಂದ್ವಿ!", "namaskaara mari! naavu bandvi!", "Hello dear! We've arrived!"), answers: [L("ಸ್ವಾಗತ ತಾತ! ಪ್ರಯಾಣ ಹೇಗಿತ್ತು?", "swaagata taata! prayaaNa heegittu?", "Welcome Tata! How was the journey?"), L("ತಾತ! ನಿಮ್ಮನ್ನು ನೋಡಿ ತುಂಬಾ ಖುಷಿ!", "taata! nimmannu nooDi tumbaa khushi!", "Tata! So happy to see you!")] },
      { gini: L("ತುಂಬಾ ಉದ್ದ ಪ್ರಯಾಣ. ಸ್ವಲ್ಪ ಸುಸ್ತಾಗಿದೆ.", "tumbaa udda prayaaNa. swalpa sustaagide.", "Very long journey. I'm a bit tired."), answers: [L("ಸ್ವಲ್ಪ ವಿಶ್ರಾಂತಿ ತಗೊಳ್ಳಿ.", "swalpa vishraanti tagoLLi.", "Please rest a little."), L("ಕಾಫಿ ಬೇಕಾ ತಾತ?", "kaaphi beekaa taata?", "Would you like coffee, Tata?")] },
      { gini: L("ಇಲ್ಲಿ ಎಷ್ಟು ಚಳಿ!", "illi eshTu chaLi!", "It's so cold here!"), answers: [L("ಸ್ವೆಟರ್ ಹಾಕಿಕೊಳ್ಳಿ.", "sweTar haakikoLLi.", "Please wear a sweater."), L("ಹೌದು, ಇಲ್ಲಿ ಚಳಿಗಾಲ.", "haudu, illi chaLigaala.", "Yes, it's winter here.")] },
      { gini: L("ನಾಳೆ ಎಲ್ಲಿಗೆ ಹೋಗೋಣ?", "naaLe ellige hoogooNa?", "Where shall we go tomorrow?"), answers: [L("ಪಾರ್ಕ್‌ಗೆ ಹೋಗೋಣ!", "paark-ge hoogooNa!", "Let's go to the park!"), L("ನನ್ನ ಶಾಲೆ ತೋರಿಸ್ತೀನಿ.", "nanna shaale tooristiini.", "I'll show you my school.")] },
    ],
  },
  {
    id: "temple", icon: "🛕", en: "At the temple", kn: "ದೇವಸ್ಥಾನದಲ್ಲಿ", for: "all", who: "Amma",
    goal: "What to say and do at the temple, from slippers to prasada.",
    phrases: [
      L("ದೇವಸ್ಥಾನಕ್ಕೆ ಹೋಗೋಣ.", "deevasthaanakke hoogooNa.", "Let's go to the temple."),
      L("ಚಪ್ಪಲಿ ಇಲ್ಲಿ ಬಿಡು.", "chappali illi biDu.", "Leave your slippers here."),
      L("ಕೈ ಮುಗಿ.", "kai mugi.", "Fold your hands."),
      L("ದೇವರಿಗೆ ನಮಸ್ಕಾರ ಮಾಡು.", "deevarige namaskaara maaDu.", "Bow to God."),
      L("ಗಂಟೆ ಬಾರಿಸು.", "ganTe baarisu.", "Ring the bell."),
      L("ಪ್ರಸಾದ ತಗೋ.", "prasaada tagoo.", "Take the prasada."),
      L("ಬಲಗೈಯಲ್ಲಿ ತಗೋ.", "balagaiyalli tagoo.", "Take it with your right hand."),
      L("ಮೆಲ್ಲಗೆ ಮಾತಾಡು.", "mellage maataaDu.", "Speak softly."),
      L("ಪ್ರದಕ್ಷಿಣೆ ಹಾಕೋಣ.", "pradakshiNe haakooNa.", "Let's walk around the shrine."),
      L("ಆರತಿ ಶುರುವಾಯ್ತು.", "aarati shuruvaaytu.", "The aarati has started."),
      L("ತೀರ್ಥ ತಗೊಳ್ಳಿ.", "tiirtha tagoLLi.", "Please take the tiirtha (holy water)."),
      L("ಎಲ್ಲರಿಗೂ ಒಳ್ಳೆಯದಾಗಲಿ.", "ellariguu oLLeyadaagali.", "May all be well."),
    ],
    chat: [
      { gini: L("ಬಾ, ದೇವಸ್ಥಾನಕ್ಕೆ ಬಂದ್ವಿ. ಚಪ್ಪಲಿ ಎಲ್ಲಿ ಬಿಡ್ತೀಯಾ?", "baa, deevasthaanakke bandvi. chappali elli biDtiiyaa?", "Come, we're at the temple. Where will you leave your slippers?"), answers: [L("ಇಲ್ಲಿ ಬಿಡ್ತೀನಿ ಅಮ್ಮ.", "illi biDtiini amma.", "I'll leave them here, Amma."), L("ಚಪ್ಪಲಿ ಸ್ಟ್ಯಾಂಡ್‌ನಲ್ಲಿ.", "chappali sTyaanD-nalli.", "On the slipper stand.")] },
      { gini: L("ಈಗ ದೇವರಿಗೆ ಕೈ ಮುಗಿ.", "iiga deevarige kai mugi.", "Now fold your hands to God."), answers: [L("ನಮಸ್ಕಾರ ದೇವರೇ!", "namaskaara deevaree!", "Namaskara, God!"), L("ನಾನು ಗಂಟೆ ಬಾರಿಸ್ಲಾ?", "naanu ganTe baarislaa?", "Shall I ring the bell?")] },
      { gini: L("ಪ್ರಸಾದ ತಗೋ. ಯಾವ ಕೈಯಲ್ಲಿ ತಗೋತೀಯಾ?", "prasaada tagoo. yaava kaiyalli tagootiiyaa?", "Take the prasada. Which hand do you use?"), answers: [L("ಬಲಗೈಯಲ್ಲಿ!", "balagaiyalli!", "The right hand!"), L("ಬಲಗೈ, ಅಮ್ಮ.", "balagai, amma.", "Right hand, Amma.")] },
      { gini: L("ಶಭಾಷ್! ಪ್ರಸಾದ ಹೇಗಿದೆ?", "shabhaash! prasaada heegide?", "Well done! How's the prasada?"), answers: [L("ತುಂಬಾ ರುಚಿಯಾಗಿದೆ!", "tumbaa ruchiyaagide!", "It's very tasty!"), L("ಇನ್ನೂ ಸ್ವಲ್ಪ ಬೇಕು!", "innuu swalpa beeku!", "I want a little more!")] },
    ],
  },
  {
    id: "festivals", icon: "🪔", en: "Festivals at home", kn: "ಹಬ್ಬದ ಮಾತು", for: "all", who: "Amma",
    goal: "Ugadi, Sankranti, Ganesha, Deepavali and Rajyotsava wishes and words.",
    phrases: [
      L("ಹಬ್ಬದ ಶುಭಾಶಯಗಳು!", "habbada shubhaashayagaLu!", "Happy festival!"),
      L("ಯುಗಾದಿ ಹಬ್ಬದ ಶುಭಾಶಯಗಳು!", "yugaadi habbada shubhaashayagaLu!", "Happy Ugadi!"),
      L("ಬೇವು ಬೆಲ್ಲ ತಿನ್ನು.", "beevu bella tinnu.", "Eat the bevu-bella (neem and jaggery)."),
      L("ಎಳ್ಳು ಬೆಲ್ಲ ತಿಂದು ಒಳ್ಳೆ ಮಾತಾಡು.", "eLLu bella tindu oLLe maataaDu.", "Eat ellu-bella and speak sweet words (Sankranti)."),
      L("ಗಣೇಶನಿಗೆ ಮೋದಕ ಇಷ್ಟ.", "gaNeeshanige moodaka ishTa.", "Ganesha loves modaka."),
      L("ದೀಪಾವಳಿ ಹಬ್ಬದ ಶುಭಾಶಯಗಳು!", "diipaavaLi habbada shubhaashayagaLu!", "Happy Deepavali!"),
      L("ದೀಪ ಹಚ್ಚೋಣ.", "diipa hachchooNa.", "Let's light the lamps."),
      L("ರಂಗೋಲಿ ಹಾಕೋಣ.", "rangooli haakooNa.", "Let's draw rangoli."),
      L("ಹೊಸ ಬಟ್ಟೆ ಹಾಕಿಕೋ.", "hosa baTTe haakikoo.", "Wear your new clothes."),
      L("ಹಿರಿಯರ ಕಾಲಿಗೆ ನಮಸ್ಕಾರ ಮಾಡು.", "hiriyara kaalige namaskaara maaDu.", "Bow to the elders (touch their feet)."),
      L("ಹೋಳಿಗೆ ಮಾಡೋಣ.", "hooLige maaDooNa.", "Let's make holige (obbattu)."),
      L("ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವದ ಶುಭಾಶಯಗಳು!", "kannaDa raajyootsavada shubhaashayagaLu!", "Happy Kannada Rajyotsava!"),
    ],
    chat: [
      { gini: L("ಇವತ್ತು ದೀಪಾವಳಿ! ಏನು ಮಾಡೋಣ?", "ivattu diipaavaLi! eenu maaDooNa?", "Today is Deepavali! What shall we do?"), answers: [L("ದೀಪ ಹಚ್ಚೋಣ!", "diipa hachchooNa!", "Let's light the lamps!"), L("ರಂಗೋಲಿ ಹಾಕೋಣ!", "rangooli haakooNa!", "Let's draw rangoli!")] },
      { gini: L("ಒಳ್ಳೆ ಐಡಿಯಾ! ಹೊಸ ಬಟ್ಟೆ ಹಾಕಿಕೊಂಡೆಯಾ?", "oLLe aiDiyaa! hosa baTTe haakikonDeyaa?", "Good idea! Did you put on new clothes?"), answers: [L("ಹೌದು, ನೋಡು!", "haudu, nooDu!", "Yes, look!"), L("ಇನ್ನೂ ಇಲ್ಲ, ಈಗ ಹಾಕ್ತೀನಿ.", "innuu illa, iiga haaktiini.", "Not yet, I'll put them on now.")] },
      { gini: L("ಅಜ್ಜಿಗೆ ಏನು ಹೇಳ್ತೀಯಾ?", "ajjige eenu heeLtiiyaa?", "What will you say to Ajji?"), answers: [L("ದೀಪಾವಳಿ ಹಬ್ಬದ ಶುಭಾಶಯಗಳು ಅಜ್ಜಿ!", "diipaavaLi habbada shubhaashayagaLu ajji!", "Happy Deepavali, Ajji!"), L("ಹಬ್ಬದ ಶುಭಾಶಯಗಳು!", "habbada shubhaashayagaLu!", "Happy festival!")] },
      { gini: L("ತುಂಬಾ ಚೆನ್ನಾಗಿ ಹೇಳಿದೆ! ಸಿಹಿ ಬೇಕಾ?", "tumbaa chennaagi heeLide! sihi beekaa?", "You said it so well! Want a sweet?"), answers: [L("ಹೌದು, ಬೇಕು!", "haudu, beeku!", "Yes please!"), L("ಎರಡು ಬೇಕು!", "eraDu beeku!", "I want two!")] },
    ],
  },
  {
    id: "kitchen", icon: "🍛", en: "In the kitchen", kn: "ಅಡುಗೆ ಮನೆಯಲ್ಲಿ", for: "all", who: "Amma",
    goal: "Cooking together, tasting, and saying how good it is.",
    phrases: [
      L("ಇವತ್ತು ಏನು ಅಡುಗೆ?", "ivattu eenu aDuge?", "What's cooking today?"),
      L("ದೋಸೆ ಮಾಡೋಣ.", "doose maaDooNa.", "Let's make dosa."),
      L("ನಾನು ಸಹಾಯ ಮಾಡ್ತೀನಿ.", "naanu sahaaya maaDtiini.", "I'll help."),
      L("ಹುಷಾರು, ಬಿಸಿ ಇದೆ!", "hushaaru, bisi ide!", "Careful, it's hot!"),
      L("ಉಪ್ಪು ಸಾಕಾ?", "uppu saakaa?", "Is there enough salt?"),
      L("ಸ್ವಲ್ಪ ಖಾರ ಜಾಸ್ತಿ.", "swalpa khaara jaasti.", "It's a bit too spicy."),
      L("ತುಂಬಾ ರುಚಿಯಾಗಿದೆ!", "tumbaa ruchiyaagide!", "It's delicious!"),
      L("ನನಗೆ ಹಸಿವಾಗ್ತಿದೆ.", "nanage hasivaagtide.", "I'm getting hungry."),
      L("ತಟ್ಟೆ ತಗೊಂಡು ಬಾ.", "taTTe tagonDu baa.", "Bring the plate."),
      L("ಇನ್ನೊಂದು ದೋಸೆ ಬೇಕು.", "innondu doose beeku.", "I want another dosa."),
      L("ಸಾಕು, ಹೊಟ್ಟೆ ತುಂಬಿತು.", "saaku, hoTTe tumbitu.", "Enough, I'm full."),
      L("ಕೈ ತೊಳೆದುಕೋ.", "kai toLedukoo.", "Wash your hands."),
    ],
    chat: [
      { gini: L("ಇವತ್ತು ದೋಸೆ ಮಾಡ್ತೀನಿ. ಸಹಾಯ ಮಾಡ್ತೀಯಾ?", "ivattu doose maaDtiini. sahaaya maaDtiiyaa?", "I'm making dosa today. Will you help?"), answers: [L("ಹೌದು, ಸಹಾಯ ಮಾಡ್ತೀನಿ!", "haudu, sahaaya maaDtiini!", "Yes, I'll help!"), L("ನಾನು ತಟ್ಟೆ ತರ್ತೀನಿ.", "naanu taTTe tartiini.", "I'll bring the plates.")] },
      { gini: L("ಮೊದಲು ಕೈ ತೊಳೆದುಕೋ.", "modalu kai toLedukoo.", "First wash your hands."), answers: [L("ತೊಳೆದೆ ಅಮ್ಮ!", "toLede amma!", "I washed them, Amma!"), L("ಆಯ್ತು, ಈಗ ತೊಳೀತೀನಿ.", "aaytu, iiga toLiitiini.", "Okay, washing now.")] },
      { gini: L("ದೋಸೆ ರೆಡಿ! ಹೇಗಿದೆ?", "doose reDi! heegide?", "Dosa's ready! How is it?"), answers: [L("ತುಂಬಾ ರುಚಿಯಾಗಿದೆ!", "tumbaa ruchiyaagide!", "It's delicious!"), L("ಸ್ವಲ್ಪ ಖಾರ ಜಾಸ್ತಿ.", "swalpa khaara jaasti.", "A bit too spicy.")] },
      { gini: L("ಇನ್ನೊಂದು ಬೇಕಾ?", "innondu beekaa?", "Want another one?"), answers: [L("ಹೌದು, ಇನ್ನೊಂದು ಬೇಕು!", "haudu, innondu beeku!", "Yes, one more!"), L("ಸಾಕು, ಹೊಟ್ಟೆ ತುಂಬಿತು.", "saaku, hoTTe tumbitu.", "Enough, I'm full.")] },
    ],
  },
  {
    id: "bedtime", icon: "🌙", en: "Morning and bedtime", kn: "ಬೆಳಿಗ್ಗೆ ಮತ್ತು ರಾತ್ರಿ", for: "kids", who: "Appa",
    goal: "The daily routine: waking up, school, stories and good night.",
    phrases: [
      L("ಶುಭೋದಯ!", "shubhoodaya!", "Good morning!"),
      L("ಏಳು, ಶಾಲೆಗೆ ಹೊತ್ತಾಯ್ತು.", "eeLu, shaalege hottaaytu.", "Get up, it's time for school."),
      L("ಹಲ್ಲು ಉಜ್ಜು.", "hallu ujju.", "Brush your teeth."),
      L("ಸ್ನಾನ ಮಾಡು.", "snaana maaDu.", "Take a bath."),
      L("ತಿಂಡಿ ತಿನ್ನು.", "tinDi tinnu.", "Eat your breakfast."),
      L("ಬ್ಯಾಗ್ ತಗೋ.", "byaag tagoo.", "Take your bag."),
      L("ಆಟ ಸಾಕು, ಮಲಗೋ ಸಮಯ.", "aaTa saaku, malagoo samaya.", "Enough play, it's bedtime."),
      L("ಕಥೆ ಹೇಳು!", "kathe heeLu!", "Tell me a story!"),
      L("ಲೈಟ್ ಆರಿಸು.", "laiT aarisu.", "Turn off the light."),
      L("ಶುಭ ರಾತ್ರಿ.", "shubha raatri.", "Good night."),
      L("ಸಿಹಿ ಕನಸು.", "sihi kanasu.", "Sweet dreams."),
      L("ನಿನ್ನನ್ನು ತುಂಬಾ ಪ್ರೀತಿಸ್ತೀನಿ.", "ninnannu tumbaa priitistiini.", "I love you very much."),
    ],
    chat: [
      { gini: L("ಆಟ ಸಾಕು, ಮಲಗೋ ಸಮಯ ಆಯ್ತು!", "aaTa saaku, malagoo samaya aaytu!", "Enough play, it's bedtime!"), answers: [L("ಇನ್ನೂ ಐದು ನಿಮಿಷ!", "innuu aidu nimisha!", "Five more minutes!"), L("ಆಯ್ತು ಅಪ್ಪ.", "aaytu appa.", "Okay, Appa.")] },
      { gini: L("ಹಲ್ಲು ಉಜ್ಜಿದೆಯಾ?", "hallu ujjideyaa?", "Did you brush your teeth?"), answers: [L("ಹೌದು, ಉಜ್ಜಿದೆ!", "haudu, ujjide!", "Yes, I brushed!"), L("ಇಲ್ಲ, ಈಗ ಉಜ್ಜುತ್ತೀನಿ.", "illa, iiga ujjuttiini.", "No, I'll brush now.")] },
      { gini: L("ಯಾವ ಕಥೆ ಬೇಕು?", "yaava kathe beeku?", "Which story do you want?"), answers: [L("ಕಾಗೆ ಕಥೆ ಹೇಳು!", "kaage kathe heeLu!", "Tell the crow story!"), L("ಸಿಂಹದ ಕಥೆ!", "simhada kathe!", "The lion story!")] },
      { gini: L("ಶುಭ ರಾತ್ರಿ, ಸಿಹಿ ಕನಸು!", "shubha raatri, sihi kanasu!", "Good night, sweet dreams!"), answers: [L("ಶುಭ ರಾತ್ರಿ ಅಪ್ಪ!", "shubha raatri appa!", "Good night, Appa!"), L("ನಿನ್ನನ್ನು ಪ್ರೀತಿಸ್ತೀನಿ ಅಪ್ಪ!", "ninnannu priitistiini appa!", "I love you, Appa!")] },
    ],
  },
  {
    id: "playdate", icon: "⚽", en: "Playing with friends", kn: "ಗೆಳೆಯರ ಜೊತೆ ಆಟ", for: "kids", who: "a friend",
    goal: "Playdates with Kannada-speaking friends: games, turns, winning and losing.",
    phrases: [
      L("ಬಾ, ಆಡೋಣ!", "baa, aaDooNa!", "Come, let's play!"),
      L("ಯಾವ ಆಟ ಆಡೋಣ?", "yaava aaTa aaDooNa?", "Which game shall we play?"),
      L("ಕಣ್ಣಾಮುಚ್ಚಾಲೆ ಆಡೋಣ.", "kaNNaamuchchaale aaDooNa.", "Let's play hide-and-seek."),
      L("ನನ್ನ ಸರದಿ!", "nanna saradi!", "My turn!"),
      L("ನಿನ್ನ ಸರದಿ.", "ninna saradi.", "Your turn."),
      L("ಓಡು! ಬೇಗ!", "ooDu! beega!", "Run! Quick!"),
      L("ನಾನು ಗೆದ್ದೆ!", "naanu gedde!", "I won!"),
      L("ಪರವಾಗಿಲ್ಲ, ಮತ್ತೆ ಆಡೋಣ.", "paravaagilla, matte aaDooNa.", "It's okay, let's play again."),
      L("ನನ್ನ ಆಟಿಕೆ ನೋಡು.", "nanna aaTike nooDu.", "Look at my toy."),
      L("ಒಟ್ಟಿಗೆ ಆಡೋಣ.", "oTTige aaDooNa.", "Let's play together."),
      L("ಕ್ಷಮಿಸು.", "kshamisu.", "Sorry."),
      L("ನೀನು ನನ್ನ ಒಳ್ಳೆಯ ಗೆಳೆಯ.", "niinu nanna oLLeya geLeya.", "You're my good friend."),
    ],
    chat: [
      { gini: L("ಹಾಯ್! ಬಾ, ಆಡೋಣ!", "haay! baa, aaDooNa!", "Hi! Come, let's play!"), answers: [L("ಯಾವ ಆಟ ಆಡೋಣ?", "yaava aaTa aaDooNa?", "Which game shall we play?"), L("ಹೌದು, ಆಡೋಣ!", "haudu, aaDooNa!", "Yes, let's play!")] },
      { gini: L("ಕಣ್ಣಾಮುಚ್ಚಾಲೆ ಆಡೋಣ?", "kaNNaamuchchaale aaDooNa?", "Shall we play hide-and-seek?"), answers: [L("ಆಯ್ತು! ನಾನು ಅಡಗಿಕೊಳ್ತೀನಿ.", "aaytu! naanu aDagikoLtiini.", "Okay! I'll hide."), L("ಬೇಡ, ಬಾಲ್ ಆಡೋಣ.", "beeDa, baal aaDooNa.", "No, let's play ball.")] },
      { gini: L("ನಾನು ಗೆದ್ದೆ!", "naanu gedde!", "I won!"), answers: [L("ಪರವಾಗಿಲ್ಲ, ಮತ್ತೆ ಆಡೋಣ.", "paravaagilla, matte aaDooNa.", "It's okay, let's play again."), L("ಈಗ ನನ್ನ ಸರದಿ!", "iiga nanna saradi!", "Now it's my turn!")] },
      { gini: L("ನೀನು ತುಂಬಾ ಚೆನ್ನಾಗಿ ಆಡ್ತೀಯಾ!", "niinu tumbaa chennaagi aaDtiiyaa!", "You play really well!"), answers: [L("ಧನ್ಯವಾದ! ನಾಳೆ ಮತ್ತೆ ಆಡೋಣ.", "dhanyavaada! naaLe matte aaDooNa.", "Thanks! Let's play again tomorrow."), L("ನೀನು ನನ್ನ ಒಳ್ಳೆಯ ಗೆಳೆಯ!", "niinu nanna oLLeya geLeya!", "You're my good friend!")] },
    ],
  },
  {
    id: "respect", icon: "🙏", en: "Talking to elders", kn: "ಹಿರಿಯರ ಜೊತೆ ಮಾತು", for: "all", who: "Tata",
    goal: "The polite ನೀವು, please and thank you, and welcoming elders home.",
    phrases: [
      L("ನೀವು / ನೀನು", "niivu / niinu", "'You': niivu for elders and new people, niinu for friends and little ones"),
      L("ಬನ್ನಿ, ಕುಳಿತುಕೊಳ್ಳಿ.", "banni, kuLitukoLLi.", "Please come in and sit down."),
      L("ನೀರು ಬೇಕಾ?", "niiru beekaa?", "Would you like water?"),
      L("ದಯವಿಟ್ಟು.", "dayaviTTu.", "Please."),
      L("ಧನ್ಯವಾದಗಳು.", "dhanyavaadagaLu.", "Thank you (polite)."),
      L("ಕ್ಷಮಿಸಿ.", "kshamisi.", "Sorry / excuse me (polite)."),
      L("ಊಟ ಮಾಡಿ.", "uuTa maaDi.", "Please eat."),
      L("ಮತ್ತೆ ಹೇಳ್ತೀರಾ?", "matte heeLtiiraa?", "Could you say that again?"),
      L("ನಿಧಾನವಾಗಿ ಹೇಳಿ.", "nidhaanavaagi heeLi.", "Please say it slowly."),
      L("ಆಶೀರ್ವಾದ ಮಾಡಿ.", "aashiirvaada maaDi.", "Please bless me."),
      L("ಹೋಗಿ ಬರ್ತೀನಿ.", "hoogi bartiini.", "I'll be off (we say 'I'll go and come back', never just 'bye')."),
      L("ಹುಷಾರಾಗಿ ಹೋಗಿ ಬನ್ನಿ.", "hushaaraagi hoogi banni.", "Go safely and come again."),
    ],
    chat: [
      { gini: L("ನಮಸ್ಕಾರ! ಒಳಗೆ ಬರಬಹುದಾ?", "namaskaara! oLage barabahudaa?", "Hello! May I come in?"), answers: [L("ಬನ್ನಿ ತಾತ, ಕುಳಿತುಕೊಳ್ಳಿ.", "banni taata, kuLitukoLLi.", "Come in Tata, please sit."), L("ನಮಸ್ಕಾರ ತಾತ! ಬನ್ನಿ.", "namaskaara taata! banni.", "Namaskara Tata! Come in.")] },
      { gini: L("ಹೊರಗೆ ತುಂಬಾ ಬಿಸಿಲು ಇದೆ.", "horage tumbaa bisilu ide.", "It's very sunny outside."), answers: [L("ನೀರು ಬೇಕಾ ತಾತ?", "niiru beekaa taata?", "Would you like water, Tata?"), L("ಕಾಫಿ ಮಾಡ್ಲಾ?", "kaaphi maaDlaa?", "Shall I make coffee?")] },
      { gini: L("ನಿನಗೆ ಕನ್ನಡ ಚೆನ್ನಾಗಿ ಬರುತ್ತೆ! ಯಾರು ಹೇಳಿಕೊಟ್ಟರು?", "ninage kannaDa chennaagi barutte! yaaru heeLikoTTaru?", "You speak Kannada well! Who taught you?"), answers: [L("ಅಮ್ಮ ಹೇಳಿಕೊಟ್ಟರು.", "amma heeLikoTTaru.", "Amma taught me."), L("ಚಿಲಿಪಿಲಿಯಲ್ಲಿ ಕಲಿತೆ!", "chilipiliyalli kalite!", "I learnt it on Chili Pili!")] },
      { gini: L("ಶಭಾಷ್! ನಾನು ಹೊರಡ್ತೀನಿ.", "shabhaash! naanu horaDtiini.", "Well done! I'll be leaving."), answers: [L("ಹುಷಾರಾಗಿ ಹೋಗಿ ಬನ್ನಿ.", "hushaaraagi hoogi banni.", "Go safely and come again."), L("ಆಶೀರ್ವಾದ ಮಾಡಿ ತಾತ.", "aashiirvaada maaDi taata.", "Please bless me, Tata.")] },
    ],
  },
  {
    id: "koota", icon: "🎤", en: "At the Kannada Koota", kn: "ಕನ್ನಡ ಕೂಟದಲ್ಲಿ", for: "all", who: "a new friend",
    goal: "Meeting other Kannada families at community events, Rajyotsava and Ugadi programmes.",
    phrases: [
      L("ನಿಮ್ಮ ಹೆಸರೇನು?", "nimma hesareenu?", "What's your name?"),
      L("ನನ್ನ ಹೆಸರು ___.", "nanna hesaru ___.", "My name is ___."),
      L("ನೀವು ಕರ್ನಾಟಕದಲ್ಲಿ ಯಾವ ಊರು?", "niivu karnaaTakadalli yaava uuru?", "Which town in Karnataka are you from?"),
      L("ನಾವು ಮೈಸೂರಿನವರು.", "naavu maisuurinavaru.", "We're from Mysuru."),
      L("ನೀವು ಇಲ್ಲಿ ಎಷ್ಟು ವರ್ಷದಿಂದ ಇದ್ದೀರಾ?", "niivu illi eshTu varshadinda iddiiraa?", "How many years have you been here?"),
      L("ಕಾರ್ಯಕ್ರಮ ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು.", "kaaryakrama tumbaa chennaagittu.", "The programme was great."),
      L("ನಿಮ್ಮ ಮಗು ಚೆನ್ನಾಗಿ ಹಾಡಿತು.", "nimma magu chennaagi haaDitu.", "Your child sang beautifully."),
      L("ನಮ್ಮ ಮಕ್ಕಳು ಒಟ್ಟಿಗೆ ಆಡಲಿ.", "namma makkaLu oTTige aaDali.", "Let our kids play together."),
      L("ನಿಮ್ಮ ನಂಬರ್ ಕೊಡ್ತೀರಾ?", "nimma nambar koDtiiraa?", "Could you give me your number?"),
      L("ಮುಂದಿನ ಕಾರ್ಯಕ್ರಮ ಯಾವಾಗ?", "mundina kaaryakrama yaavaaga?", "When is the next event?"),
      L("ಸಿರಿಗನ್ನಡಂ ಗೆಲ್ಗೆ!", "sirigannaDam gelge!", "Long live glorious Kannada!"),
      L("ಜೈ ಕರ್ನಾಟಕ ಮಾತೆ!", "jai karnaaTaka maate!", "Victory to Mother Karnataka!"),
    ],
    chat: [
      { gini: L("ನಮಸ್ಕಾರ! ನಿಮ್ಮ ಹೆಸರೇನು?", "namaskaara! nimma hesareenu?", "Hello! What's your name?"), answers: [L("ನನ್ನ ಹೆಸರು ಮೀರಾ.", "nanna hesaru miiraa.", "My name is Meera."), L("ನಮಸ್ಕಾರ! ನಾನು ಅರ್ಜುನ್.", "namaskaara! naanu arjun.", "Hello! I'm Arjun.")] },
      { gini: L("ಚೆಂದದ ಹೆಸರು! ಕರ್ನಾಟಕದಲ್ಲಿ ಯಾವ ಊರು?", "chendada hesaru! karnaaTakadalli yaava uuru?", "Lovely name! Which town in Karnataka?"), answers: [L("ನಾವು ಬೆಂಗಳೂರಿನವರು.", "naavu bengaLuurinavaru.", "We're from Bengaluru."), L("ನಮ್ಮ ಅಜ್ಜಿ ಮೈಸೂರಿನಲ್ಲಿ ಇದ್ದಾರೆ.", "namma ajji maisuurinalli iddaare.", "Our Ajji lives in Mysuru.")] },
      { gini: L("ಕಾರ್ಯಕ್ರಮ ಹೇಗಿತ್ತು?", "kaaryakrama heegittu?", "How was the programme?"), answers: [L("ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು!", "tumbaa chennaagittu!", "It was great!"), L("ಹಾಡು ತುಂಬಾ ಇಷ್ಟ ಆಯ್ತು.", "haaDu tumbaa ishTa aaytu.", "I loved the song.")] },
      { gini: L("ಮುಂದಿನ ಸಲ ಒಟ್ಟಿಗೆ ಆಡೋಣ!", "mundina sala oTTige aaDooNa!", "Let's play together next time!"), answers: [L("ಆಯ್ತು! ಸಿಗೋಣ!", "aaytu! sigooNa!", "Okay! See you!"), L("ಜೈ ಕರ್ನಾಟಕ!", "jai karnaaTaka!", "Jai Karnataka!")] },
    ],
  },
  {
    id: "wedding", icon: "💐", en: "Weddings and family functions", kn: "ಮದುವೆ ಮತ್ತು ಸಮಾರಂಭ", for: "grown", who: "an aunty",
    goal: "Introducing yourself to relatives, congratulating, and the banana-leaf meal.",
    phrases: [
      L("ನಮಸ್ಕಾರ ಆಂಟಿ, ಹೇಗಿದ್ದೀರಾ?", "namaskaara aanTi, heegiddiiraa?", "Hello aunty, how are you?"),
      L("ನಾನು ___ ಅವರ ಮಗ / ಮಗಳು.", "naanu ___ avara maga / magaLu.", "I'm ___'s son / daughter."),
      L("ನಾನು ___ ಅವರ ಹೆಂಡತಿ / ಗಂಡ.", "naanu ___ avara henDati / ganDa.", "I'm ___'s wife / husband."),
      L("ಮದುವೆಗೆ ಅಭಿನಂದನೆಗಳು!", "maduvege abhinandanegaLu!", "Congratulations on the wedding!"),
      L("ಮುಹೂರ್ತ ಎಷ್ಟು ಗಂಟೆಗೆ?", "muhuurta eshTu ganTege?", "What time is the muhurta?"),
      L("ಊಟ ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು.", "uuTa tumbaa chennaagittu.", "The meal was very good."),
      L("ಬಾಳೆ ಎಲೆ ಊಟ ಮೊದಲ ಸಲ!", "baaLe ele uuTa modala sala!", "My first banana-leaf meal!"),
      L("ಸೀರೆ ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ.", "siire tumbaa chennaagide.", "The saree is lovely."),
      L("ನಿಮ್ಮನ್ನು ನೋಡಿ ಖುಷಿ ಆಯ್ತು.", "nimmannu nooDi khushi aaytu.", "Lovely to meet you."),
      L("ಆಶೀರ್ವಾದ ಮಾಡಿ.", "aashiirvaada maaDi.", "Please bless us."),
      L("ನಮ್ಮ ಮನೆಗೆ ಬನ್ನಿ.", "namma manege banni.", "Please come to our home."),
      L("ನನಗೆ ಸ್ವಲ್ಪ ಸ್ವಲ್ಪ ಕನ್ನಡ ಬರುತ್ತೆ.", "nanage swalpa swalpa kannaDa barutte.", "I know a little Kannada."),
    ],
    chat: [
      { gini: L("ನಮಸ್ಕಾರ! ನೀವು ಯಾರು ಅಂತ ಗೊತ್ತಾಗ್ಲಿಲ್ಲ.", "namaskaara! niivu yaaru anta gottaaglilla.", "Hello! I didn't recognise you."), answers: [L("ನಾನು ಪ್ರಿಯಾ, ರವಿ ಅವರ ಹೆಂಡತಿ.", "naanu priyaa, ravi avara henDati.", "I'm Priya, Ravi's wife."), L("ನಾನು ಅಮೆರಿಕದಿಂದ ಬಂದಿದ್ದೀನಿ.", "naanu amerikadinda bandiddiini.", "I've come from America.")] },
      { gini: L("ಓ, ತುಂಬಾ ಖುಷಿ! ನಿಮಗೆ ಕನ್ನಡ ಬರುತ್ತಾ?", "oo, tumbaa khushi! nimage kannaDa baruttaa?", "Oh, so nice! Do you know Kannada?"), answers: [L("ಸ್ವಲ್ಪ ಸ್ವಲ್ಪ ಬರುತ್ತೆ.", "swalpa swalpa barutte.", "A little bit."), L("ಕಲಿತಾ ಇದ್ದೀನಿ!", "kalitaa iddiini!", "I'm learning!")] },
      { gini: L("ತುಂಬಾ ಚೆನ್ನಾಗಿ ಮಾತಾಡ್ತೀರಾ! ಊಟ ಆಯ್ತಾ?", "tumbaa chennaagi maataaDtiiraa! uuTa aaytaa?", "You speak very well! Have you eaten?"), answers: [L("ಹೌದು, ಊಟ ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು.", "haudu, uuTa tumbaa chennaagittu.", "Yes, the meal was very good."), L("ಇನ್ನೂ ಇಲ್ಲ, ಈಗ ಹೋಗ್ತೀನಿ.", "innuu illa, iiga hoogtiini.", "Not yet, I'm going now.")] },
      { gini: L("ಮತ್ತೆ ಸಿಗೋಣ! ನಮ್ಮ ಮನೆಗೆ ಬನ್ನಿ.", "matte sigooNa! namma manege banni.", "See you again! Come to our home."), answers: [L("ಖಂಡಿತ ಬರ್ತೀವಿ. ಧನ್ಯವಾದ!", "khanDita bartiivi. dhanyavaada!", "We'll surely come. Thank you!"), L("ನಿಮ್ಮನ್ನು ನೋಡಿ ಖುಷಿ ಆಯ್ತು.", "nimmannu nooDi khushi aaytu.", "Lovely to meet you.")] },
    ],
  },
  {
    id: "unwell", icon: "🩺", en: "Health and feeling unwell", kn: "ಆರೋಗ್ಯ", for: "grown", who: "Ajji",
    goal: "Looking after a visiting elder: aches, tablets, the doctor.",
    phrases: [
      L("ಹುಷಾರಿಲ್ವಾ?", "hushaarilvaa?", "Not feeling well?"),
      L("ಎಲ್ಲಿ ನೋವಾಗ್ತಿದೆ?", "elli noovaagtide?", "Where does it hurt?"),
      L("ತಲೆ ನೋವು.", "tale noovu.", "Headache."),
      L("ಹೊಟ್ಟೆ ನೋವು.", "hoTTe noovu.", "Stomach ache."),
      L("ಜ್ವರ ಇದೆಯಾ?", "jvara ideyaa?", "Do you have a fever?"),
      L("ಮಾತ್ರೆ ತಗೊಂಡ್ರಾ?", "maatre tagonDraa?", "Did you take your tablets?"),
      L("ಡಾಕ್ಟರ್ ಹತ್ರ ಹೋಗೋಣ.", "DaakTar hatra hoogooNa.", "Let's go to the doctor."),
      L("ಬಿಸಿ ನೀರು ಕುಡಿಯಿರಿ.", "bisi niiru kuDiyiri.", "Please drink warm water."),
      L("ವಿಶ್ರಾಂತಿ ತಗೊಳ್ಳಿ.", "vishraanti tagoLLi.", "Please rest."),
      L("ಈಗ ಹೇಗಿದೆ?", "iiga heegide?", "How is it now?"),
      L("ಸ್ವಲ್ಪ ಪರವಾಗಿಲ್ಲ.", "swalpa paravaagilla.", "A little better."),
      L("ಏನಾದ್ರೂ ಬೇಕಾದ್ರೆ ಕರೀರಿ.", "eenaadruu beekaadre kariiri.", "Call me if you need anything."),
    ],
    chat: [
      { gini: L("ಇವತ್ತು ಯಾಕೋ ಹುಷಾರಿಲ್ಲ.", "ivattu yaakoo hushaarilla.", "I'm somehow not well today."), answers: [L("ಎಲ್ಲಿ ನೋವಾಗ್ತಿದೆ ಅಜ್ಜಿ?", "elli noovaagtide ajji?", "Where does it hurt, Ajji?"), L("ಜ್ವರ ಇದೆಯಾ?", "jvara ideyaa?", "Do you have a fever?")] },
      { gini: L("ತಲೆ ನೋವು, ಸ್ವಲ್ಪ ಸುಸ್ತು.", "tale noovu, swalpa sustu.", "Headache, and a bit tired."), answers: [L("ಮಾತ್ರೆ ತಗೊಂಡ್ರಾ?", "maatre tagonDraa?", "Did you take your tablets?"), L("ವಿಶ್ರಾಂತಿ ತಗೊಳ್ಳಿ.", "vishraanti tagoLLi.", "Please rest.")] },
      { gini: L("ಹೌದು, ತಗೊಂಡೆ.", "haudu, tagonDe.", "Yes, I took them."), answers: [L("ಬಿಸಿ ನೀರು ಕೊಡ್ತೀನಿ.", "bisi niiru koDtiini.", "I'll get you warm water."), L("ಡಾಕ್ಟರ್ ಹತ್ರ ಹೋಗೋಣವಾ?", "DaakTar hatra hoogooNavaa?", "Shall we go to the doctor?")] },
      { gini: L("ಬೇಡ, ಸ್ವಲ್ಪ ಮಲಗ್ತೀನಿ.", "beeDa, swalpa malagtiini.", "No need, I'll lie down a bit."), answers: [L("ಏನಾದ್ರೂ ಬೇಕಾದ್ರೆ ಕರೀರಿ.", "eenaadruu beekaadre kariiri.", "Call me if you need anything."), L("ಆಯ್ತು ಅಜ್ಜಿ, ಹುಷಾರಾಗಿ.", "aaytu ajji, hushaaraagi.", "Okay Ajji, get well soon.")] },
    ],
  },
  {
    id: "trip", icon: "🛺", en: "Visiting Karnataka", kn: "ಕರ್ನಾಟಕ ಪ್ರವಾಸ", for: "grown", who: "an auto driver",
    goal: "Autos, directions, darshini breakfasts and shopping on your trip home.",
    phrases: [
      L("ಆಟೋ! ಮೀಟರ್ ಹಾಕಿ.", "aaTo! miiTar haaki.", "Auto! Please put the meter on."),
      L("ಮೆಜೆಸ್ಟಿಕ್‌ಗೆ ಬರ್ತೀರಾ?", "mejesTik-ge bartiiraa?", "Will you come to Majestic?"),
      L("ಎಷ್ಟು ಆಗುತ್ತೆ?", "eshTu aagutte?", "How much will it be?"),
      L("ತುಂಬಾ ಜಾಸ್ತಿ, ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ.", "tumbaa jaasti, swalpa kaDime maaDi.", "Too much, please make it a little less."),
      L("ಇಲ್ಲೇ ನಿಲ್ಲಿಸಿ.", "illee nillisi.", "Stop right here."),
      L("ಬಲಕ್ಕೆ ಹೋಗಿ. ಎಡಕ್ಕೆ ಹೋಗಿ.", "balakke hoogi. eDakke hoogi.", "Go right. Go left."),
      L("ನೇರವಾಗಿ ಹೋಗಿ.", "neeravaagi hoogi.", "Go straight."),
      L("ಒಂದು ಮಸಾಲೆ ದೋಸೆ, ಒಂದು ಕಾಫಿ.", "ondu masaale doose, ondu kaaphi.", "One masala dosa, one coffee."),
      L("ಬಿಲ್ ಕೊಡಿ.", "bil koDi.", "The bill, please."),
      L("ಇದು ಎಷ್ಟು?", "idu eshTu?", "How much is this?"),
      L("ಟಾಯ್ಲೆಟ್ ಎಲ್ಲಿದೆ?", "Taaylet ellide?", "Where's the toilet?"),
      L("ನಾವು ಅಮೆರಿಕದಿಂದ ಬಂದಿದ್ದೀವಿ.", "naavu amerikadinda bandiddiivi.", "We've come from America."),
    ],
    chat: [
      { gini: L("ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?", "ellige hoogabeeku?", "Where do you want to go?"), answers: [L("ಮೆಜೆಸ್ಟಿಕ್‌ಗೆ ಹೋಗಬೇಕು.", "mejesTik-ge hoogabeeku.", "I need to go to Majestic."), L("ಲಾಲ್‌ಬಾಗ್‌ಗೆ ಬರ್ತೀರಾ?", "laalbaag-ge bartiiraa?", "Will you come to Lalbagh?")] },
      { gini: L("ಮುನ್ನೂರು ರೂಪಾಯಿ ಆಗುತ್ತೆ.", "munnuuru ruupaayi aagutte.", "It'll be three hundred rupees."), answers: [L("ತುಂಬಾ ಜಾಸ್ತಿ! ಮೀಟರ್ ಹಾಕಿ.", "tumbaa jaasti! miiTar haaki.", "Too much! Put the meter on."), L("ಇನ್ನೂರು ಆಗಲ್ವಾ?", "innuuru aagalvaa?", "Won't two hundred do?")] },
      { gini: L("ಸರಿ, ಕುಳಿತುಕೊಳ್ಳಿ. ಎಲ್ಲಿಂದ ಬಂದಿದ್ದೀರಾ?", "sari, kuLitukoLLi. ellinda bandiddiiraa?", "Okay, sit down. Where have you come from?"), answers: [L("ನಾವು ಅಮೆರಿಕದಿಂದ ಬಂದಿದ್ದೀವಿ.", "naavu amerikadinda bandiddiivi.", "We've come from America."), L("ನಮ್ಮ ಊರು ಮೈಸೂರು.", "namma uuru maisuuru.", "Our hometown is Mysuru.")] },
      { gini: L("ಓಹ್! ಕನ್ನಡ ಚೆನ್ನಾಗಿ ಮಾತಾಡ್ತೀರಾ!", "ooh! kannaDa chennaagi maataaDtiiraa!", "Oh! You speak Kannada well!"), answers: [L("ಧನ್ಯವಾದ! ಕಲಿತಾ ಇದ್ದೀನಿ.", "dhanyavaada! kalitaa iddiini.", "Thanks! I'm learning."), L("ಇಲ್ಲೇ ನಿಲ್ಲಿಸಿ, ಪ್ಲೀಸ್.", "illee nillisi, pliis.", "Stop right here, please.")] },
    ],
  },
];

export const packsFor = (kid) => PACKS.filter((p) => (kid ? p.for !== "grown" : true));
export const packById = (id) => PACKS.find((p) => p.id === id);
