// Stories for Big writers (level 4) and the Story corner. One story a week.
// q: [question, correct answer, other answer, other answer] (answers are shuffled on screen).
// Please have a Kannada teacher review every line before families use it.

export const STORIES = [
  {
    id: "crow", en: "The thirsty crow", kn: "ಬಾಯಾರಿದ ಕಾಗೆ", pic: "🐦‍⬛",
    lines: ["ಒಂದು ಬೇಸಿಗೆಯ ದಿನ ತುಂಬಾ ಬಿಸಿಲು ಇತ್ತು.", "ಒಂದು ಕಾಗೆಗೆ ತುಂಬಾ ಬಾಯಾರಿಕೆ ಆಯಿತು.", "ಅದು ನೀರಿಗಾಗಿ ಎಲ್ಲಾ ಕಡೆ ಹುಡುಕಿತು.", "ಕೊನೆಗೆ ಅದಕ್ಕೆ ಒಂದು ಮಡಕೆ ಕಾಣಿಸಿತು.", "ಮಡಕೆಯ ತಳದಲ್ಲಿ ಸ್ವಲ್ಪ ನೀರು ಇತ್ತು.", "ಕಾಗೆ ಚಿಕ್ಕ ಕಲ್ಲುಗಳನ್ನು ತಂದು ಮಡಕೆಗೆ ಹಾಕಿತು.", "ನೀರು ನಿಧಾನವಾಗಿ ಮೇಲೆ ಬಂತು.", "ಕಾಗೆ ನೀರು ಕುಡಿದು ಖುಷಿಯಿಂದ ಹಾರಿ ಹೋಯಿತು."],
    en_lines: ["One summer day it was very sunny.", "A crow became very thirsty.", "It looked everywhere for water.", "At last it saw a pot.", "There was a little water at the bottom of the pot.", "The crow brought small stones and dropped them into the pot.", "Slowly the water came up.", "The crow drank the water and flew away happily."],
    words: [["ಬಾಯಾರಿಕೆ", "baayaarike", "thirst", "🥵"], ["ಮಡಕೆ", "maDake", "pot", "🏺"], ["ಕಲ್ಲು", "kallu", "stone", "🪨"], ["ತಳ", "taLa", "bottom", "⬇️"]],
    q: [["ಕಾಗೆಗೆ ಏನು ಆಯಿತು?", "ಬಾಯಾರಿಕೆ ಆಯಿತು", "ಹಸಿವು ಆಯಿತು", "ನಿದ್ದೆ ಬಂತು"], ["ಮಡಕೆಯಲ್ಲಿ ಎಷ್ಟು ನೀರು ಇತ್ತು?", "ಸ್ವಲ್ಪ ನೀರು", "ತುಂಬಾ ನೀರು", "ನೀರು ಇರಲೇ ಇಲ್ಲ"], ["ಕಾಗೆ ಮಡಕೆಗೆ ಏನು ಹಾಕಿತು?", "ಕಲ್ಲುಗಳು", "ಎಲೆಗಳು", "ಹೂವುಗಳು"]],
    write: "Write 5 sentences about a time you were very thirsty or hungry. What did you do?", bank: ["ಬಾಯಾರಿಕೆ", "ನೀರು", "ಕುಡಿದೆ", "ಖುಷಿ"],
  },
  {
    id: "lion-mouse", en: "The lion and the mouse", kn: "ಸಿಂಹ ಮತ್ತು ಇಲಿ", pic: "🦁",
    lines: ["ಒಂದು ಕಾಡಿನಲ್ಲಿ ಒಂದು ದೊಡ್ಡ ಸಿಂಹ ಇತ್ತು.", "ಒಂದು ದಿನ ಸಿಂಹ ಮರದ ಕೆಳಗೆ ಮಲಗಿತ್ತು.", "ಒಂದು ಚಿಕ್ಕ ಇಲಿ ಅದರ ಮೇಲೆ ಓಡಾಡಿತು.", "ಸಿಂಹ ಎದ್ದು ಇಲಿಯನ್ನು ಹಿಡಿಯಿತು.", "\"ದಯವಿಟ್ಟು ನನ್ನನ್ನು ಬಿಡು, ನಾನು ನಿನಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ\" ಎಂದು ಇಲಿ ಹೇಳಿತು.", "ಸಿಂಹ ನಕ್ಕು ಇಲಿಯನ್ನು ಬಿಟ್ಟಿತು.", "ಕೆಲವು ದಿನಗಳ ನಂತರ ಸಿಂಹ ಒಂದು ಬಲೆಯಲ್ಲಿ ಸಿಕ್ಕಿಕೊಂಡಿತು.", "ಇಲಿ ಬಂದು ಬಲೆಯನ್ನು ಕಚ್ಚಿ ಸಿಂಹವನ್ನು ಬಿಡಿಸಿತು."],
    en_lines: ["In a forest there was a big lion.", "One day the lion was sleeping under a tree.", "A little mouse ran over it.", "The lion woke up and caught the mouse.", "\"Please let me go, I will help you,\" said the mouse.", "The lion laughed and let the mouse go.", "A few days later the lion was caught in a net.", "The mouse came, bit through the net and set the lion free."],
    words: [["ಸಿಂಹ", "simha", "lion", "🦁"], ["ಇಲಿ", "ili", "mouse", "🐭"], ["ಬಲೆ", "bale", "net", "🕸️"], ["ಸಹಾಯ", "sahaaya", "help", "🤝"]],
    q: [["ಸಿಂಹ ಎಲ್ಲಿ ಮಲಗಿತ್ತು?", "ಮರದ ಕೆಳಗೆ", "ನದಿಯ ಹತ್ತಿರ", "ಗುಹೆಯಲ್ಲಿ"], ["ಸಿಂಹ ಇಲಿಯನ್ನು ಏನು ಮಾಡಿತು?", "ಬಿಟ್ಟಿತು", "ತಿಂದಿತು", "ಓಡಿಸಿತು"], ["ಇಲಿ ಸಿಂಹಕ್ಕೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಿತು?", "ಬಲೆಯನ್ನು ಕಚ್ಚಿತು", "ನೀರು ತಂದಿತು", "ಹಾಡು ಹಾಡಿತು"]],
    write: "Write about a time someone helped you, or you helped someone. 5 sentences.", bank: ["ಸಹಾಯ", "ಗೆಳೆಯ", "ಖುಷಿ", "ಧನ್ಯವಾದ"],
  },
  {
    id: "hare-tortoise", en: "The hare and the tortoise", kn: "ಮೊಲ ಮತ್ತು ಆಮೆ", pic: "🐢",
    lines: ["ಒಂದು ಕಾಡಿನಲ್ಲಿ ಒಂದು ಮೊಲ ಮತ್ತು ಒಂದು ಆಮೆ ಇದ್ದವು.", "ಮೊಲ ತುಂಬಾ ವೇಗವಾಗಿ ಓಡುತ್ತಿತ್ತು.", "ಆಮೆ ನಿಧಾನವಾಗಿ ನಡೆಯುತ್ತಿತ್ತು.", "ಒಂದು ದಿನ ಅವು ಓಟದ ಸ್ಪರ್ಧೆ ಮಾಡಿದವು.", "ಮೊಲ ಮುಂದೆ ಓಡಿ ಹೋಗಿ ಮರದ ಕೆಳಗೆ ಮಲಗಿತು.", "ಆಮೆ ನಿಲ್ಲದೆ ನಡೆಯುತ್ತಲೇ ಇತ್ತು.", "ಮೊಲ ಎದ್ದಾಗ ಆಮೆ ಗೆದ್ದಿತ್ತು.", "ನಿಧಾನವಾದರೂ ನಿಲ್ಲದೆ ಹೋದರೆ ಗೆಲ್ಲಬಹುದು."],
    en_lines: ["In a forest there lived a hare and a tortoise.", "The hare ran very fast.", "The tortoise walked slowly.", "One day they had a race.", "The hare ran ahead and slept under a tree.", "The tortoise kept walking without stopping.", "When the hare woke up, the tortoise had won.", "Slow but steady can win."],
    words: [["ಮೊಲ", "mola", "hare", "🐇"], ["ಆಮೆ", "aame", "tortoise", "🐢"], ["ಓಟ", "ooTa", "race", "🏁"], ["ಸ್ಪರ್ಧೆ", "spardhe", "competition", "🏆"]],
    q: [["ಯಾರು ವೇಗವಾಗಿ ಓಡುತ್ತಿತ್ತು?", "ಮೊಲ", "ಆಮೆ", "ಆನೆ"], ["ಓಟದ ನಡುವೆ ಮೊಲ ಏನು ಮಾಡಿತು?", "ಮಲಗಿತು", "ತಿಂದಿತು", "ಹಾಡಿತು"], ["ಓಟದಲ್ಲಿ ಯಾರು ಗೆದ್ದರು?", "ಆಮೆ", "ಮೊಲ", "ಯಾರೂ ಇಲ್ಲ"]],
    write: "Write about a race or game you played. Who won? How did you feel? 5 sentences.", bank: ["ಓಡಿದೆ", "ಗೆದ್ದೆ", "ಸೋತೆ", "ಖುಷಿ"],
  },
  {
    id: "fox-grapes", en: "The fox and the grapes", kn: "ನರಿ ಮತ್ತು ದ್ರಾಕ್ಷಿ", pic: "🦊",
    lines: ["ಒಂದು ದಿನ ಒಂದು ನರಿಗೆ ತುಂಬಾ ಹಸಿವಾಗಿತ್ತು.", "ಅದು ಒಂದು ತೋಟಕ್ಕೆ ಹೋಯಿತು.", "ಅಲ್ಲಿ ಎತ್ತರದಲ್ಲಿ ಕಪ್ಪು ದ್ರಾಕ್ಷಿ ಗೊಂಚಲುಗಳು ಇದ್ದವು.", "ನರಿ ಹಾರಿ ಹಾರಿ ದ್ರಾಕ್ಷಿ ಹಿಡಿಯಲು ಪ್ರಯತ್ನಿಸಿತು.", "ಆದರೆ ದ್ರಾಕ್ಷಿ ತುಂಬಾ ಎತ್ತರದಲ್ಲಿ ಇತ್ತು.", "ನರಿಗೆ ಸುಸ್ತಾಯಿತು.", "\"ಈ ದ್ರಾಕ್ಷಿ ಹುಳಿ\" ಎಂದು ಹೇಳಿ ನರಿ ಹೊರಟು ಹೋಯಿತು."],
    en_lines: ["One day a fox was very hungry.", "It went into a garden.", "High up there were bunches of black grapes.", "The fox jumped and jumped to reach the grapes.", "But the grapes were too high.", "The fox got tired.", "\"These grapes are sour,\" said the fox, and walked away."],
    words: [["ನರಿ", "nari", "fox", "🦊"], ["ದ್ರಾಕ್ಷಿ", "draakshi", "grapes", "🍇"], ["ಗೊಂಚಲು", "gonchalu", "bunch", "🍇"], ["ಹುಳಿ", "huLi", "sour", "🍋"]],
    q: [["ನರಿ ಎಲ್ಲಿಗೆ ಹೋಯಿತು?", "ತೋಟಕ್ಕೆ", "ಶಾಲೆಗೆ", "ನದಿಗೆ"], ["ದ್ರಾಕ್ಷಿ ಎಲ್ಲಿ ಇತ್ತು?", "ಎತ್ತರದಲ್ಲಿ", "ನೆಲದ ಮೇಲೆ", "ಮಡಕೆಯಲ್ಲಿ"], ["ನರಿ ಕೊನೆಗೆ ಏನು ಹೇಳಿತು?", "ದ್ರಾಕ್ಷಿ ಹುಳಿ", "ದ್ರಾಕ್ಷಿ ಸಿಹಿ", "ನನಗೆ ಹಸಿವಿಲ್ಲ"]],
    write: "Write about something you really wanted but couldn't get. What did you do? 5 sentences.", bank: ["ಬೇಕು", "ಆದರೆ", "ಪ್ರಯತ್ನಿಸಿದೆ", "ಬೇಸರ"],
  },
  {
    id: "greedy-dog", en: "The greedy dog", kn: "ದುರಾಸೆಯ ನಾಯಿ", pic: "🐕",
    lines: ["ಒಂದು ನಾಯಿಗೆ ಒಂದು ಮೂಳೆ ಸಿಕ್ಕಿತು.", "ಅದು ಮೂಳೆಯನ್ನು ಬಾಯಲ್ಲಿ ಹಿಡಿದು ಮನೆಗೆ ಹೊರಟಿತು.", "ದಾರಿಯಲ್ಲಿ ಒಂದು ಸೇತುವೆ ಇತ್ತು.", "ಕೆಳಗೆ ನೀರಿನಲ್ಲಿ ನಾಯಿ ತನ್ನ ನೆರಳನ್ನು ನೋಡಿತು.", "ಅದು ಇನ್ನೊಂದು ನಾಯಿ ಎಂದು ಅಂದುಕೊಂಡಿತು.", "ಆ ಮೂಳೆಯೂ ಬೇಕು ಎಂದು ಅದು ಬೊಗಳಿತು.", "ಅದರ ಬಾಯಿಯ ಮೂಳೆ ನೀರಿಗೆ ಬಿದ್ದು ಹೋಯಿತು.", "ದುರಾಸೆಯಿಂದ ಇದ್ದದ್ದೂ ಹೋಯಿತು."],
    en_lines: ["A dog found a bone.", "It held the bone in its mouth and set off home.", "On the way there was a bridge.", "Below, in the water, the dog saw its reflection.", "It thought it was another dog.", "Wanting that bone too, it barked.", "The bone in its mouth fell into the water.", "Being greedy, it lost what it had."],
    words: [["ಮೂಳೆ", "muuLe", "bone", "🦴"], ["ಸೇತುವೆ", "seetuve", "bridge", "🌉"], ["ನೆರಳು", "neraLu", "reflection", "🪞"], ["ದುರಾಸೆ", "duraase", "greed", "😋"]],
    q: [["ನಾಯಿಗೆ ಏನು ಸಿಕ್ಕಿತು?", "ಮೂಳೆ", "ಚೆಂಡು", "ರೊಟ್ಟಿ"], ["ನೀರಿನಲ್ಲಿ ನಾಯಿ ಏನು ನೋಡಿತು?", "ತನ್ನ ನೆರಳು", "ಮೀನು", "ಕಪ್ಪೆ"], ["ನಾಯಿ ಬೊಗಳಿದಾಗ ಏನಾಯಿತು?", "ಮೂಳೆ ನೀರಿಗೆ ಬಿತ್ತು", "ನಾಯಿ ಹಾರಿತು", "ಮಳೆ ಬಂತು"]],
    write: "Write 5 sentences about sharing. When did you share something? How did it feel?", bank: ["ಹಂಚಿಕೊಂಡೆ", "ಗೆಳೆಯ", "ಖುಷಿ", "ಕೊಟ್ಟೆ"],
  },
  {
    id: "monkey-croc", en: "The monkey and the crocodile", kn: "ಕೋತಿ ಮತ್ತು ಮೊಸಳೆ", pic: "🐒",
    lines: ["ನದಿಯ ದಡದಲ್ಲಿ ಒಂದು ನೇರಳೆ ಮರ ಇತ್ತು.", "ಆ ಮರದಲ್ಲಿ ಒಂದು ಕೋತಿ ಇರುತ್ತಿತ್ತು.", "ಕೋತಿ ದಿನಾ ಮೊಸಳೆಗೆ ಸಿಹಿ ಹಣ್ಣುಗಳನ್ನು ಕೊಡುತ್ತಿತ್ತು.", "ಒಂದು ದಿನ ಮೊಸಳೆ ಕೋತಿಯನ್ನು ಬೆನ್ನ ಮೇಲೆ ಕೂರಿಸಿಕೊಂಡು ನದಿಗೆ ಹೋಯಿತು.", "\"ನನ್ನ ಹೆಂಡತಿಗೆ ನಿನ್ನ ಹೃದಯ ಬೇಕು\" ಎಂದು ಮೊಸಳೆ ಹೇಳಿತು.", "ಜಾಣ ಕೋತಿ \"ನನ್ನ ಹೃದಯ ಮರದ ಮೇಲೆ ಇದೆ\" ಎಂದು ಹೇಳಿತು.", "ಮೊಸಳೆ ಕೋತಿಯನ್ನು ದಡಕ್ಕೆ ಕರೆದುಕೊಂಡು ಬಂತು.", "ಕೋತಿ ಬೇಗ ಮರ ಹತ್ತಿ ತಪ್ಪಿಸಿಕೊಂಡಿತು."],
    en_lines: ["On the river bank there was a jamun tree.", "A monkey lived in that tree.", "Every day the monkey gave the crocodile sweet fruits.", "One day the crocodile carried the monkey on its back into the river.", "\"My wife wants your heart,\" said the crocodile.", "The clever monkey said, \"My heart is up in the tree.\"", "The crocodile brought the monkey back to the bank.", "The monkey quickly climbed the tree and escaped."],
    words: [["ಮೊಸಳೆ", "mosaLe", "crocodile", "🐊"], ["ದಡ", "daDa", "river bank", "🏞️"], ["ಬೆನ್ನು", "bennu", "back", "🔙"], ["ಜಾಣ", "jaaNa", "clever", "🧠"]],
    q: [["ಕೋತಿ ಎಲ್ಲಿ ಇರುತ್ತಿತ್ತು?", "ಮರದಲ್ಲಿ", "ನದಿಯಲ್ಲಿ", "ಮನೆಯಲ್ಲಿ"], ["ಕೋತಿ ಮೊಸಳೆಗೆ ಏನು ಕೊಡುತ್ತಿತ್ತು?", "ಹಣ್ಣುಗಳು", "ಮೀನು", "ಹೂವುಗಳು"], ["ಕೋತಿ ಹೇಗೆ ತಪ್ಪಿಸಿಕೊಂಡಿತು?", "ಜಾಣತನದಿಂದ", "ಅಳುವುದರಿಂದ", "ಮಲಗುವುದರಿಂದ"]],
    write: "Write about a time you had to think fast. What happened? 5 sentences.", bank: ["ಯೋಚಿಸಿದೆ", "ಜಾಣ", "ಬೇಗ", "ಕೊನೆಗೆ"],
  },
  {
    id: "ant", en: "The ant and the grasshopper", kn: "ಇರುವೆ ಮತ್ತು ಮಿಡತೆ", pic: "🐜",
    lines: ["ಬೇಸಿಗೆಯಲ್ಲಿ ಒಂದು ಇರುವೆ ದಿನವೂ ಕೆಲಸ ಮಾಡುತ್ತಿತ್ತು.", "ಅದು ಕಾಳುಗಳನ್ನು ತನ್ನ ಮನೆಗೆ ಹೊತ್ತು ಒಯ್ಯುತ್ತಿತ್ತು.", "ಒಂದು ಮಿಡತೆ ಹಾಡುತ್ತಾ ಕುಣಿಯುತ್ತಾ ಇತ್ತು.", "\"ಬಾ, ಆಟ ಆಡೋಣ\" ಎಂದು ಮಿಡತೆ ಕರೆಯಿತು.", "\"ಚಳಿಗಾಲಕ್ಕೆ ಊಟ ಬೇಕು\" ಎಂದು ಇರುವೆ ಹೇಳಿತು.", "ಚಳಿಗಾಲ ಬಂದಾಗ ಮಿಡತೆಗೆ ತಿನ್ನಲು ಏನೂ ಇರಲಿಲ್ಲ.", "ಇರುವೆ ಮನೆಯಲ್ಲಿ ಬೆಚ್ಚಗೆ ಊಟ ಮಾಡುತ್ತಿತ್ತು.", "ಮುಂದಿನ ದಿನಗಳಿಗಾಗಿ ಈಗಲೇ ಕೆಲಸ ಮಾಡಬೇಕು."],
    en_lines: ["In summer an ant worked every day.", "It carried grains to its home.", "A grasshopper was singing and dancing.", "\"Come, let's play,\" called the grasshopper.", "\"We need food for winter,\" said the ant.", "When winter came, the grasshopper had nothing to eat.", "The ant was eating, warm at home.", "We should work now for the days ahead."],
    words: [["ಇರುವೆ", "iruve", "ant", "🐜"], ["ಮಿಡತೆ", "miDate", "grasshopper", "🦗"], ["ಕಾಳು", "kaaLu", "grain", "🌾"], ["ಚಳಿಗಾಲ", "chaLigaala", "winter", "❄️"]],
    q: [["ಬೇಸಿಗೆಯಲ್ಲಿ ಇರುವೆ ಏನು ಮಾಡುತ್ತಿತ್ತು?", "ಕೆಲಸ", "ಹಾಡು", "ನಿದ್ದೆ"], ["ಮಿಡತೆ ಏನು ಮಾಡುತ್ತಿತ್ತು?", "ಹಾಡುತ್ತಾ ಕುಣಿಯುತ್ತಿತ್ತು", "ಕಾಳು ತರುತ್ತಿತ್ತು", "ಮನೆ ಕಟ್ಟುತ್ತಿತ್ತು"], ["ಚಳಿಗಾಲದಲ್ಲಿ ಯಾರ ಹತ್ತಿರ ಊಟ ಇತ್ತು?", "ಇರುವೆ", "ಮಿಡತೆ", "ಯಾರ ಹತ್ತಿರವೂ ಇಲ್ಲ"]],
    write: "What do you do to get ready for school or a trip? Write 5 sentences with ಮೊದಲು, ಆಮೇಲೆ, ಕೊನೆಗೆ.", bank: ["ಮೊದಲು", "ಆಮೇಲೆ", "ಕೊನೆಗೆ", "ತಯಾರಿ"],
  },
  {
    id: "rain", en: "A rainy day", kn: "ಮಳೆಯ ದಿನ", pic: "🌧️",
    lines: ["ಇಂದು ಬೆಳಿಗ್ಗೆಯಿಂದ ಜೋರಾಗಿ ಮಳೆ ಬರುತ್ತಿತ್ತು.", "ಅನು ಮತ್ತು ಅವಳ ತಮ್ಮ ಹೊರಗೆ ಆಡಲು ಹೋಗಲಿಲ್ಲ.", "ಅವರು ಕಿಟಕಿಯ ಹತ್ತಿರ ಕುಳಿತು ಮಳೆಯನ್ನು ನೋಡಿದರು.", "ಅಮ್ಮ ಬಿಸಿ ಬಿಸಿ ಬಜ್ಜಿ ಮಾಡಿದರು.", "ಅನು ಕಾಗದದ ದೋಣಿ ಮಾಡಿದಳು.", "ಮಳೆ ನಿಂತ ಮೇಲೆ ಅವರು ಹೊರಗೆ ಹೋಗಿ ದೋಣಿಯನ್ನು ನೀರಿನಲ್ಲಿ ಬಿಟ್ಟರು.", "ದೋಣಿ ತೇಲುತ್ತಾ ದೂರ ಹೋಯಿತು.", "ಅದು ತುಂಬಾ ಖುಷಿಯ ದಿನ."],
    en_lines: ["Today it had been raining hard since morning.", "Anu and her little brother didn't go out to play.", "They sat by the window and watched the rain.", "Amma made hot bajji.", "Anu made a paper boat.", "When the rain stopped they went out and put the boat in the water.", "The boat floated far away.", "It was a very happy day."],
    words: [["ಮಳೆ", "maLe", "rain", "🌧️"], ["ಕಿಟಕಿ", "kiTaki", "window", "🪟"], ["ದೋಣಿ", "dooNi", "boat", "⛵"], ["ತೇಲು", "teelu", "float", "🛟"]],
    q: [["ಅನು ಏಕೆ ಹೊರಗೆ ಹೋಗಲಿಲ್ಲ?", "ಮಳೆ ಬರುತ್ತಿತ್ತು", "ಅವಳಿಗೆ ಜ್ವರ ಇತ್ತು", "ಕತ್ತಲಾಗಿತ್ತು"], ["ಅಮ್ಮ ಏನು ಮಾಡಿದರು?", "ಬಜ್ಜಿ", "ದೋಸೆ", "ಕೇಕ್"], ["ಅನು ಏನು ಮಾಡಿದಳು?", "ಕಾಗದದ ದೋಣಿ", "ಗಾಳಿಪಟ", "ಚಿತ್ರ"]],
    write: "Write about a rainy or snowy day at your home. What did you see, eat and do? 6 sentences.", bank: ["ಮಳೆ", "ಹಿಮ", "ಕಿಟಕಿ", "ಆಡಿದೆವು"],
  },
  {
    id: "birthday", en: "My birthday", kn: "ನನ್ನ ಹುಟ್ಟುಹಬ್ಬ", pic: "🎂",
    lines: ["ನಿನ್ನೆ ನನ್ನ ಹುಟ್ಟುಹಬ್ಬ ಇತ್ತು.", "ಬೆಳಿಗ್ಗೆ ಅಮ್ಮ ಅಪ್ಪ \"ಹುಟ್ಟುಹಬ್ಬದ ಶುಭಾಶಯಗಳು\" ಎಂದು ಹೇಳಿದರು.", "ನಾನು ಹೊಸ ಬಟ್ಟೆ ಹಾಕಿಕೊಂಡೆ.", "ಸಂಜೆ ನನ್ನ ಗೆಳೆಯರು ಮನೆಗೆ ಬಂದರು.", "ನಾವು ಆಟ ಆಡಿದೆವು ಮತ್ತು ಹಾಡು ಹಾಡಿದೆವು.", "ಅಜ್ಜಿ ಭಾರತದಿಂದ ವಿಡಿಯೋ ಕರೆ ಮಾಡಿದರು.", "ನಾನು ಕೇಕ್ ಕತ್ತರಿಸಿದೆ.", "ಅದು ನನ್ನ ತುಂಬಾ ಖುಷಿಯ ದಿನ."],
    en_lines: ["Yesterday was my birthday.", "In the morning Amma and Appa said \"Happy birthday\".", "I wore new clothes.", "In the evening my friends came home.", "We played games and sang songs.", "Ajji video-called from India.", "I cut the cake.", "It was my happiest day."],
    words: [["ಹುಟ್ಟುಹಬ್ಬ", "huTTuhabba", "birthday", "🎂"], ["ಶುಭಾಶಯ", "shubhaashaya", "wishes", "🎉"], ["ಕರೆ", "kare", "call", "📞"], ["ಕತ್ತರಿಸು", "kattarisu", "cut", "🔪"]],
    q: [["ನಿನ್ನೆ ಏನು ಇತ್ತು?", "ಹುಟ್ಟುಹಬ್ಬ", "ಹಬ್ಬ", "ರಜೆ"], ["ಸಂಜೆ ಯಾರು ಬಂದರು?", "ಗೆಳೆಯರು", "ಶಿಕ್ಷಕರು", "ಯಾರೂ ಬರಲಿಲ್ಲ"], ["ಅಜ್ಜಿ ಏನು ಮಾಡಿದರು?", "ವಿಡಿಯೋ ಕರೆ ಮಾಡಿದರು", "ಕೇಕ್ ತಂದರು", "ಹಾಡು ಹಾಡಿದರು"]],
    write: "Write about your last birthday (or a friend's) in 6 sentences: who came, what you ate, what you did.", bank: ["ಹುಟ್ಟುಹಬ್ಬ", "ಗೆಳೆಯರು", "ಕೇಕ್", "ಉಡುಗೊರೆ"],
  },
  {
    id: "ganesha", en: "Our Ganesha festival", kn: "ನಮ್ಮ ಗಣೇಶ ಹಬ್ಬ", pic: "🪔",
    lines: ["ನಾವು ಪ್ರತಿ ವರ್ಷ ಗಣೇಶ ಹಬ್ಬ ಆಚರಿಸುತ್ತೇವೆ.", "ಅಪ್ಪ ಮಣ್ಣಿನ ಗಣೇಶನನ್ನು ಮನೆಗೆ ತರುತ್ತಾರೆ.", "ನಾನು ಮತ್ತು ಅಕ್ಕ ಹೂವುಗಳಿಂದ ಅಲಂಕಾರ ಮಾಡುತ್ತೇವೆ.", "ಅಮ್ಮ ಮೋದಕ ಮತ್ತು ಕಡುಬು ಮಾಡುತ್ತಾರೆ.", "ನಾವು ಎಲ್ಲರೂ ಸೇರಿ ಪೂಜೆ ಮಾಡುತ್ತೇವೆ.", "ಗೆಳೆಯರು ಮತ್ತು ನೆಂಟರು ಮನೆಗೆ ಬರುತ್ತಾರೆ.", "ಗಣೇಶನಿಗೆ ಮೋದಕ ತುಂಬಾ ಇಷ್ಟ.", "ನನಗೂ ಮೋದಕ ತುಂಬಾ ಇಷ್ಟ!"],
    en_lines: ["We celebrate the Ganesha festival every year.", "Appa brings a clay Ganesha home.", "My big sister and I decorate with flowers.", "Amma makes modaka and kadubu.", "We all do the puja together.", "Friends and relatives come home.", "Ganesha loves modaka.", "I love modaka too!"],
    words: [["ಹಬ್ಬ", "habba", "festival", "🎉"], ["ಮಣ್ಣು", "maNNu", "clay", "🟤"], ["ಅಲಂಕಾರ", "alankaara", "decoration", "🌸"], ["ಪೂಜೆ", "puuje", "puja", "🪔"]],
    q: [["ಅಪ್ಪ ಏನು ತರುತ್ತಾರೆ?", "ಮಣ್ಣಿನ ಗಣೇಶ", "ಹೊಸ ಆಟಿಕೆ", "ಕೇಕ್"], ["ಅಮ್ಮ ಏನು ಮಾಡುತ್ತಾರೆ?", "ಮೋದಕ ಮತ್ತು ಕಡುಬು", "ದೋಸೆ", "ಪಿಜ್ಜಾ"], ["ಗಣೇಶನಿಗೆ ಏನು ಇಷ್ಟ?", "ಮೋದಕ", "ಐಸ್ ಕ್ರೀಮ್", "ಹಾಲು"]],
    write: "Write about a festival at your home in 6 sentences: before, on the day, and after.", bank: ["ಹಬ್ಬ", "ಪೂಜೆ", "ಅಲಂಕಾರ", "ಸಿಹಿ"],
  },
  {
    id: "trip", en: "A trip to Ajji's village", kn: "ಅಜ್ಜಿಯ ಊರಿಗೆ ಪಯಣ", pic: "✈️",
    lines: ["ಬೇಸಿಗೆ ರಜೆಯಲ್ಲಿ ನಾವು ಭಾರತಕ್ಕೆ ಹೋದೆವು.", "ವಿಮಾನದಲ್ಲಿ ತುಂಬಾ ಹೊತ್ತು ಕುಳಿತೆವು.", "ಬೆಂಗಳೂರಿನಿಂದ ಕಾರಿನಲ್ಲಿ ಅಜ್ಜಿಯ ಊರಿಗೆ ಹೋದೆವು.", "ಅಜ್ಜಿಯ ಮನೆಯ ಮುಂದೆ ದೊಡ್ಡ ಮಾವಿನ ಮರ ಇತ್ತು.", "ನಾನು ಅಜ್ಜನ ಜೊತೆ ಹಸುಗಳನ್ನು ನೋಡಲು ಹೋದೆ.", "ಅಜ್ಜಿ ನನಗೆ ಹೊಸ ಕಥೆಗಳನ್ನು ಹೇಳಿದರು.", "ನಾನು ದಿನಾ ಮಾವಿನ ಹಣ್ಣು ತಿಂದೆ.", "ಊರು ಬಿಟ್ಟು ಬರುವಾಗ ನನಗೆ ತುಂಬಾ ದುಃಖ ಆಯಿತು."],
    en_lines: ["In the summer holidays we went to India.", "We sat on the plane for a very long time.", "From Bengaluru we drove to Ajji's village.", "In front of Ajji's house there was a big mango tree.", "I went with Ajja to see the cows.", "Ajji told me new stories.", "I ate mangoes every day.", "When we left the village I felt very sad."],
    words: [["ಪಯಣ", "payaNa", "journey", "🧳"], ["ರಜೆ", "raje", "holiday", "🏖️"], ["ವಿಮಾನ", "vimaana", "aeroplane", "✈️"], ["ಊರು", "uuru", "village", "🏘️"]],
    q: [["ನಾವು ಯಾವಾಗ ಭಾರತಕ್ಕೆ ಹೋದೆವು?", "ಬೇಸಿಗೆ ರಜೆಯಲ್ಲಿ", "ಚಳಿಗಾಲದಲ್ಲಿ", "ಹುಟ್ಟುಹಬ್ಬಕ್ಕೆ"], ["ಅಜ್ಜಿಯ ಮನೆಯ ಮುಂದೆ ಏನು ಇತ್ತು?", "ಮಾವಿನ ಮರ", "ನದಿ", "ಶಾಲೆ"], ["ಊರು ಬಿಟ್ಟಾಗ ಹೇಗೆ ಅನಿಸಿತು?", "ದುಃಖ", "ಖುಷಿ", "ಕೋಪ"]],
    write: "Write about a trip you took, or want to take, in 6 sentences: where, how, with whom, what you did.", bank: ["ಪಯಣ", "ವಿಮಾನ", "ಊರು", "ಖುಷಿ"],
  },
  {
    id: "clever-rabbit", en: "The clever rabbit", kn: "ಜಾಣ ಮೊಲ", pic: "🐇",
    lines: ["ಒಂದು ಕಾಡಿನಲ್ಲಿ ಒಂದು ಕ್ರೂರ ಸಿಂಹ ಇತ್ತು.", "ಪ್ರಾಣಿಗಳು ಎಲ್ಲರೂ ಅದಕ್ಕೆ ಹೆದರುತ್ತಿದ್ದವು.", "ಒಂದು ದಿನ ಒಂದು ಚಿಕ್ಕ ಮೊಲ ತಡವಾಗಿ ಸಿಂಹದ ಹತ್ತಿರ ಹೋಯಿತು.", "\"ದಾರಿಯಲ್ಲಿ ಇನ್ನೊಂದು ಸಿಂಹ ಇದೆ\" ಎಂದು ಮೊಲ ಹೇಳಿತು.", "ಸಿಂಹಕ್ಕೆ ಕೋಪ ಬಂತು, ಅದು ಮೊಲದ ಜೊತೆ ಬಾವಿಯ ಹತ್ತಿರ ಹೋಯಿತು.", "ಬಾವಿಯ ನೀರಿನಲ್ಲಿ ಸಿಂಹ ತನ್ನ ನೆರಳನ್ನೇ ನೋಡಿತು.", "ಅದು ಇನ್ನೊಂದು ಸಿಂಹ ಎಂದು ಬಾವಿಗೆ ಹಾರಿತು.", "ಕಾಡಿನ ಪ್ರಾಣಿಗಳು ಸುರಕ್ಷಿತವಾದವು."],
    en_lines: ["In a forest there was a cruel lion.", "All the animals were afraid of it.", "One day a little rabbit went to the lion late.", "\"There's another lion on the way,\" said the rabbit.", "The lion got angry and went with the rabbit to a well.", "In the well's water the lion saw its own reflection.", "Thinking it was another lion, it jumped into the well.", "The animals of the forest were safe."],
    words: [["ಬಾವಿ", "baavi", "well", "🕳️"], ["ಕ್ರೂರ", "kruura", "cruel", "😠"], ["ಹೆದರು", "hedaru", "be afraid", "😨"], ["ಸುರಕ್ಷಿತ", "surakshita", "safe", "🛡️"]],
    q: [["ಪ್ರಾಣಿಗಳು ಸಿಂಹಕ್ಕೆ ಏಕೆ ಹೆದರುತ್ತಿದ್ದವು?", "ಅದು ಕ್ರೂರವಾಗಿತ್ತು", "ಅದು ಚಿಕ್ಕದಾಗಿತ್ತು", "ಅದು ಹಾಡುತ್ತಿತ್ತು"], ["ಸಿಂಹ ಬಾವಿಯಲ್ಲಿ ಏನು ನೋಡಿತು?", "ತನ್ನ ನೆರಳು", "ಮೀನು", "ಮೊಲ"], ["ಈ ಕಥೆಯಲ್ಲಿ ಯಾರು ಜಾಣ?", "ಮೊಲ", "ಸಿಂಹ", "ಆನೆ"]],
    write: "Make up your own animal story (6 to 8 sentences): who, a problem, and a clever ending.", bank: ["ಒಂದು ಕಾಡಿನಲ್ಲಿ", "ಒಂದು ದಿನ", "ಆಮೇಲೆ", "ಕೊನೆಗೆ"],
  },
  {
    id: "cats-monkey", en: "Two cats and a monkey", kn: "ಎರಡು ಬೆಕ್ಕು ಮತ್ತು ಕೋತಿ", pic: "🐒",
    lines: ["ಎರಡು ಬೆಕ್ಕುಗಳಿಗೆ ಒಂದು ರೊಟ್ಟಿ ಸಿಕ್ಕಿತು.", "ಅವು ರೊಟ್ಟಿಗಾಗಿ ಜಗಳ ಆಡಿದವು.", "ಅಲ್ಲಿಗೆ ಒಂದು ಕೋತಿ ಬಂತು.", "\"ನಾನು ರೊಟ್ಟಿಯನ್ನು ಸಮವಾಗಿ ಹಂಚುತ್ತೇನೆ\" ಎಂದು ಕೋತಿ ಹೇಳಿತು.", "ಕೋತಿ ರೊಟ್ಟಿಯನ್ನು ಎರಡು ತುಂಡು ಮಾಡಿತು.", "ಒಂದು ತುಂಡು ದೊಡ್ಡದಾಗಿತ್ತು, ಅದಕ್ಕೆ ಕೋತಿ ಸ್ವಲ್ಪ ತಿಂದಿತು.", "ಹೀಗೆ ತಿನ್ನುತ್ತಾ ತಿನ್ನುತ್ತಾ ಕೋತಿ ಇಡೀ ರೊಟ್ಟಿಯನ್ನು ತಿಂದಿತು.", "ಜಗಳ ಆಡಿದರೆ ಇಬ್ಬರಿಗೂ ನಷ್ಟ."],
    en_lines: ["Two cats found a roti.", "They fought over the roti.", "A monkey came along.", "\"I will share the roti equally,\" said the monkey.", "The monkey broke the roti into two pieces.", "One piece was bigger, so the monkey ate a little of it.", "Eating bit by bit, the monkey ate the whole roti.", "When we fight, both sides lose."],
    words: [["ಬೆಕ್ಕು", "bekku", "cat", "🐱"], ["ರೊಟ್ಟಿ", "roTTi", "roti", "🫓"], ["ಕೋತಿ", "kooti", "monkey", "🐒"], ["ಜಗಳ", "jagaLa", "fight", "😾"]],
    q: [["ಬೆಕ್ಕುಗಳಿಗೆ ಏನು ಸಿಕ್ಕಿತು?", "ರೊಟ್ಟಿ", "ಹಾಲು", "ಮೀನು"], ["ರೊಟ್ಟಿಯನ್ನು ಯಾರು ಹಂಚಿದರು?", "ಕೋತಿ", "ಆನೆ", "ನಾಯಿ"], ["ಕೊನೆಗೆ ರೊಟ್ಟಿ ಯಾರಿಗೆ ಸಿಕ್ಕಿತು?", "ಕೋತಿಗೆ", "ಬೆಕ್ಕುಗಳಿಗೆ", "ಯಾರಿಗೂ ಇಲ್ಲ"]],
    write: "Write about a time you shared something with a brother, sister or friend. 5 sentences.", bank: ["ಹಂಚಿದೆ", "ತಮ್ಮ", "ಅಕ್ಕ", "ಸ್ನೇಹಿತ"],
  },
  {
    id: "blue-jackal", en: "The blue jackal", kn: "ನೀಲಿ ನರಿ", pic: "🦊",
    lines: ["ಒಂದು ನರಿ ಆಹಾರ ಹುಡುಕುತ್ತಾ ಊರಿಗೆ ಬಂತು.", "ನಾಯಿಗಳು ಅದನ್ನು ಓಡಿಸಿದವು.", "ನರಿ ಓಡಿ ನೀಲಿ ಬಣ್ಣದ ಡಬ್ಬಿಯಲ್ಲಿ ಬಿದ್ದಿತು.", "ಅದು ಕಾಡಿಗೆ ಹಿಂತಿರುಗಿದಾಗ ಪೂರ್ತಿ ನೀಲಿ ಆಗಿತ್ತು.", "\"ನಾನು ಕಾಡಿನ ರಾಜ\" ಎಂದು ನರಿ ಹೇಳಿತು.", "ಪ್ರಾಣಿಗಳು ಹೆದರಿ ಅದಕ್ಕೆ ಆಹಾರ ತಂದು ಕೊಟ್ಟವು.", "ಒಂದು ರಾತ್ರಿ ನರಿಗಳು ಊಳಿಟ್ಟವು, ನೀಲಿ ನರಿಯೂ ಊಳಿಟ್ಟಿತು.", "ಆಗ ಎಲ್ಲರಿಗೂ ಸತ್ಯ ಗೊತ್ತಾಯಿತು."],
    en_lines: ["A jackal came to a town looking for food.", "The dogs chased it away.", "The jackal ran and fell into a tub of blue dye.", "When it went back to the forest, it was all blue.", "\"I am the king of the forest,\" said the jackal.", "The animals were scared and brought it food.", "One night the jackals howled, and the blue jackal howled too.", "Then everyone knew the truth."],
    words: [["ನರಿ", "nari", "jackal", "🦊"], ["ನೀಲಿ", "niili", "blue", "🔵"], ["ರಾಜ", "raaja", "king", "👑"], ["ಸತ್ಯ", "satya", "truth", "✅"]],
    q: [["ನರಿ ಯಾವುದರಲ್ಲಿ ಬಿದ್ದಿತು?", "ನೀಲಿ ಬಣ್ಣದ ಡಬ್ಬಿಯಲ್ಲಿ", "ನದಿಯಲ್ಲಿ", "ಹಳ್ಳದಲ್ಲಿ"], ["ನರಿ ತನ್ನನ್ನು ಏನು ಎಂದು ಹೇಳಿತು?", "ಕಾಡಿನ ರಾಜ", "ಒಂದು ನಾಯಿ", "ಒಂದು ಹಕ್ಕಿ"], ["ಸತ್ಯ ಹೇಗೆ ಗೊತ್ತಾಯಿತು?", "ನರಿ ಊಳಿಟ್ಟಾಗ", "ಮಳೆ ಬಂದಾಗ", "ನರಿ ಓಡಿದಾಗ"]],
    write: "Why is it important to tell the truth? Write 5 sentences.", bank: ["ಸತ್ಯ", "ಸುಳ್ಳು", "ಹೇಳಿದೆ", "ಒಳ್ಳೆಯದು"],
  },
  {
    id: "snow", en: "The first snow", kn: "ಮೊದಲ ಹಿಮ", pic: "☃️",
    lines: ["ಇವತ್ತು ಬೆಳಿಗ್ಗೆ ನಾನು ಕಿಟಕಿಯಿಂದ ಹೊರಗೆ ನೋಡಿದೆ.", "ಎಲ್ಲಾ ಕಡೆ ಬಿಳಿ ಹಿಮ ಇತ್ತು!", "ಇವತ್ತು ಶಾಲೆಗೆ ರಜೆ.", "ನಾನು ಬೆಚ್ಚನೆಯ ಕೋಟು, ಟೋಪಿ ಮತ್ತು ಕೈಗವಸು ಹಾಕಿಕೊಂಡೆ.", "ನಾನು ಮತ್ತು ತಮ್ಮ ಹಿಮದ ಮನುಷ್ಯನನ್ನು ಮಾಡಿದೆವು.", "ಅಪ್ಪ ಅದಕ್ಕೆ ಕ್ಯಾರೆಟ್ ಮೂಗು ಇಟ್ಟರು.", "ಆಮೇಲೆ ಅಮ್ಮ ಬಿಸಿ ಬಿಸಿ ಹಾಲು ಕೊಟ್ಟರು.", "ನಾನು ಅಜ್ಜಿಗೆ ಹಿಮದ ಫೋಟೋ ಕಳುಹಿಸಿದೆ."],
    en_lines: ["This morning I looked out of the window.", "There was white snow everywhere!", "No school today.", "I put on a warm coat, a hat and gloves.", "My little brother and I made a snowman.", "Appa gave it a carrot nose.", "Then Amma gave us hot milk.", "I sent Ajji a photo of the snow."],
    words: [["ಹಿಮ", "hima", "snow", "❄️"], ["ಕಿಟಕಿ", "kiTaki", "window", "🪟"], ["ಕೈಗವಸು", "kaigavasu", "gloves", "🧤"], ["ಬೆಚ್ಚನೆ", "bechchane", "warm", "🔥"]],
    q: [["ಹೊರಗೆ ಏನು ಇತ್ತು?", "ಬಿಳಿ ಹಿಮ", "ಮಳೆ", "ಬಿಸಿಲು"], ["ಅವರು ಏನು ಮಾಡಿದರು?", "ಹಿಮದ ಮನುಷ್ಯ", "ಕೇಕ್", "ಗಾಳಿಪಟ"], ["ಅಜ್ಜಿಗೆ ಏನು ಕಳುಹಿಸಿದರು?", "ಹಿಮದ ಫೋಟೋ", "ಒಂದು ಪತ್ರ", "ಹೂವು"]],
    write: "Write about your favourite season here: what do you see, wear and do? 5 sentences.", bank: ["ಚಳಿ", "ಹಿಮ", "ಬಿಸಿಲು", "ಆಟ"],
  },
  {
    id: "dove-ant", en: "The dove and the ant", kn: "ಪಾರಿವಾಳ ಮತ್ತು ಇರುವೆ", pic: "🕊️",
    lines: ["ಒಂದು ಇರುವೆಗೆ ಬಾಯಾರಿಕೆ ಆಯಿತು.", "ಅದು ನೀರು ಕುಡಿಯಲು ನದಿಗೆ ಹೋಯಿತು.", "ಆದರೆ ಇರುವೆ ನೀರಿನಲ್ಲಿ ಬಿದ್ದುಬಿಟ್ಟಿತು.", "ಮರದ ಮೇಲೆ ಕುಳಿತಿದ್ದ ಒಂದು ಪಾರಿವಾಳ ಅದನ್ನು ನೋಡಿತು.", "ಪಾರಿವಾಳ ಒಂದು ಎಲೆಯನ್ನು ನೀರಿಗೆ ಹಾಕಿತು.", "ಇರುವೆ ಎಲೆಯ ಮೇಲೆ ಹತ್ತಿ ದಡಕ್ಕೆ ಬಂತು.", "ಒಂದು ದಿನ ಒಬ್ಬ ಬೇಟೆಗಾರ ಪಾರಿವಾಳಕ್ಕೆ ಗುರಿ ಇಟ್ಟ.", "ಇರುವೆ ಅವನ ಕಾಲು ಕಚ್ಚಿತು, ಪಾರಿವಾಳ ಹಾರಿ ಹೋಯಿತು."],
    en_lines: ["An ant was thirsty.", "It went to the river to drink.", "But the ant fell into the water.", "A dove sitting in a tree saw it.", "The dove dropped a leaf into the water.", "The ant climbed onto the leaf and reached the bank.", "One day a hunter took aim at the dove.", "The ant bit his leg, and the dove flew away."],
    words: [["ಇರುವೆ", "iruve", "ant", "🐜"], ["ಪಾರಿವಾಳ", "paarivaaLa", "dove", "🕊️"], ["ಎಲೆ", "ele", "leaf", "🍃"], ["ನದಿ", "nadi", "river", "🏞️"]],
    q: [["ಇರುವೆ ಎಲ್ಲಿ ಬಿತ್ತು?", "ನೀರಿನಲ್ಲಿ", "ಮರದಲ್ಲಿ", "ಮನೆಯಲ್ಲಿ"], ["ಪಾರಿವಾಳ ನೀರಿಗೆ ಏನು ಹಾಕಿತು?", "ಒಂದು ಎಲೆ", "ಒಂದು ಕಲ್ಲು", "ಒಂದು ಹೂವು"], ["ಇರುವೆ ಪಾರಿವಾಳವನ್ನು ಹೇಗೆ ಉಳಿಸಿತು?", "ಬೇಟೆಗಾರನ ಕಾಲು ಕಚ್ಚಿತು", "ಹಾಡು ಹಾಡಿತು", "ಓಡಿ ಹೋಯಿತು"]],
    write: "Write about something kind someone did for you, and something kind you did back. 5 sentences.", bank: ["ಸಹಾಯ", "ಒಳ್ಳೆಯ", "ಧನ್ಯವಾದ", "ಸ್ನೇಹಿತ"],
  },
  {
    id: "library", en: "A day at the library", kn: "ಗ್ರಂಥಾಲಯದಲ್ಲಿ ಒಂದು ದಿನ", pic: "📚",
    lines: ["ಶನಿವಾರ ನಾನು ಅಪ್ಪನ ಜೊತೆ ಗ್ರಂಥಾಲಯಕ್ಕೆ ಹೋದೆ.", "ಅಲ್ಲಿ ತುಂಬಾ ಪುಸ್ತಕಗಳು ಇದ್ದವು.", "ಎಲ್ಲರೂ ಮೆಲ್ಲಗೆ ಮಾತಾಡುತ್ತಿದ್ದರು.", "ನಾನು ಡೈನೋಸಾರ್ ಬಗ್ಗೆ ಒಂದು ಪುಸ್ತಕ ಆರಿಸಿದೆ.", "ಅಪ್ಪ ಒಂದು ಕನ್ನಡ ಕಥೆ ಪುಸ್ತಕ ಹುಡುಕಿದರು.", "ಅದನ್ನು ನಾವು ಮನೆಗೆ ತಂದೆವು.", "ರಾತ್ರಿ ಅಪ್ಪ ಕನ್ನಡ ಕಥೆ ಓದಿದರು, ನಾನು ಕೇಳಿದೆ.", "ಮುಂದಿನ ವಾರ ನಾನೇ ಒಂದು ಪುಟ ಓದುತ್ತೇನೆ!"],
    en_lines: ["On Saturday I went to the library with Appa.", "There were lots of books there.", "Everyone was talking softly.", "I chose a book about dinosaurs.", "Appa found a Kannada storybook.", "We brought it home.", "At night Appa read the Kannada story and I listened.", "Next week I will read a page myself!"],
    words: [["ಗ್ರಂಥಾಲಯ", "granthaalaya", "library", "🏛️"], ["ಪುಸ್ತಕ", "pustaka", "book", "📚"], ["ಮೆಲ್ಲಗೆ", "mellage", "softly", "🤫"], ["ಪುಟ", "puTa", "page", "📄"]],
    q: [["ಅವರು ಎಲ್ಲಿಗೆ ಹೋದರು?", "ಗ್ರಂಥಾಲಯಕ್ಕೆ", "ಅಂಗಡಿಗೆ", "ಉದ್ಯಾನಕ್ಕೆ"], ["ಮಗು ಯಾವ ಪುಸ್ತಕ ಆರಿಸಿತು?", "ಡೈನೋಸಾರ್ ಪುಸ್ತಕ", "ಹಾಡಿನ ಪುಸ್ತಕ", "ಅಡುಗೆ ಪುಸ್ತಕ"], ["ರಾತ್ರಿ ಯಾರು ಕಥೆ ಓದಿದರು?", "ಅಪ್ಪ", "ಅಜ್ಜಿ", "ಶಿಕ್ಷಕಿ"]],
    write: "Write about your favourite book: what is it about, and why do you like it? 5 sentences.", bank: ["ಪುಸ್ತಕ", "ಕಥೆ", "ಇಷ್ಟ", "ಓದಿದೆ"],
  },
  {
    id: "rajyotsava", en: "Rajyotsava in our town", kn: "ನಮ್ಮ ಊರಿನ ರಾಜ್ಯೋತ್ಸವ", pic: "🎤",
    lines: ["ನವೆಂಬರ್ ಒಂದು ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವ.", "ನಮ್ಮ ಊರಿನ ಕನ್ನಡ ಕೂಟ ಒಂದು ಕಾರ್ಯಕ್ರಮ ಮಾಡಿತು.", "ಎಲ್ಲಾ ಕಡೆ ಕೆಂಪು ಮತ್ತು ಹಳದಿ ಬಾವುಟಗಳು ಇದ್ದವು.", "ನಾನು ಹೊಸ ಬಟ್ಟೆ ಹಾಕಿಕೊಂಡು ಹೋದೆ.", "ಮಕ್ಕಳು ವೇದಿಕೆಯ ಮೇಲೆ ಕನ್ನಡ ಹಾಡು ಹಾಡಿದರು.", "ನಾನು ಒಂದು ಚಿಕ್ಕ ಕವನ ಹೇಳಿದೆ.", "ಎಲ್ಲರೂ ಚಪ್ಪಾಳೆ ತಟ್ಟಿದರು.", "ಆಮೇಲೆ ನಾವು ಬಿಸಿಬೇಳೆ ಬಾತ್ ತಿಂದೆವು."],
    en_lines: ["The first of November is Kannada Rajyotsava.", "Our town's Kannada Koota held a programme.", "There were red and yellow flags everywhere.", "I wore new clothes and went.", "Children sang Kannada songs on the stage.", "I recited a short poem.", "Everyone clapped.", "Then we ate bisibele bath."],
    words: [["ಬಾವುಟ", "baavuTa", "flag", "🚩"], ["ವೇದಿಕೆ", "veedike", "stage", "🎤"], ["ಕವನ", "kavana", "poem", "📝"], ["ಚಪ್ಪಾಳೆ", "chappaaLe", "clapping", "👏"]],
    q: [["ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವ ಯಾವಾಗ?", "ನವೆಂಬರ್ ಒಂದು", "ಜನವರಿ ಒಂದು", "ಆಗಸ್ಟ್ ಹದಿನೈದು"], ["ಬಾವುಟಗಳ ಬಣ್ಣ ಯಾವುದು?", "ಕೆಂಪು ಮತ್ತು ಹಳದಿ", "ನೀಲಿ ಮತ್ತು ಬಿಳಿ", "ಹಸಿರು ಮತ್ತು ಕಪ್ಪು"], ["ಮಕ್ಕಳು ವೇದಿಕೆಯ ಮೇಲೆ ಏನು ಮಾಡಿದರು?", "ಹಾಡು ಹಾಡಿದರು", "ಮಲಗಿದರು", "ಊಟ ಮಾಡಿದರು"]],
    write: "Write about a Kannada event, festival or programme you went to. 5 sentences.", bank: ["ಹಬ್ಬ", "ಹಾಡು", "ಬಾವುಟ", "ಖುಷಿ"],
  },
];

export const storyFor = (n) => STORIES[(Math.max(1, n) - 1) % STORIES.length];
// Dictation: the shorter lines of a story.
export const dictationOf = (s, k = 3) => [...s.lines].filter((l) => !/"/.test(l)).sort((a, b) => a.length - b.length).slice(0, k);
export const RETELL = [
  { q: "ಕಥೆಯಲ್ಲಿ ಯಾರು ಇದ್ದರು?", qEn: "Who was in the story?", a: "ಕಥೆಯಲ್ಲಿ ___ ಇತ್ತು.", aEn: "In the story there was ___." },
  { q: "ಮೊದಲು ಏನಾಯಿತು?", qEn: "What happened first?", a: "ಮೊದಲು ___.", aEn: "First ___." },
  { q: "ಕೊನೆಗೆ ಏನಾಯಿತು?", qEn: "What happened in the end?", a: "ಕೊನೆಗೆ ___.", aEn: "In the end ___." },
];
